import fs from'node:fs';
import assert from'node:assert/strict';import test from'node:test';import{Bone,Group,BufferGeometry,Float32BufferAttribute,Uint16BufferAttribute,SkinnedMesh,MeshBasicMaterial,Skeleton,Quaternion,Vector3}from'three';import{StableGarmentContacts}from'./src/viewer/garmentContacts.ts';
function fixture(){const root=new Group(),hip=new Bone();hip.name='Hip';hip.position.y=.9;root.add(hip);const bones=[hip];for(const side of ['L','R']){const upper=new Bone(),lower=new Bone(),foot=new Bone();upper.name='UpLeg_'+side;lower.name='Leg_'+side;foot.name='Foot_'+side;upper.position.set(side==='L'?.1:-.1,0,0);lower.position.y=-.4;foot.position.y=-.4;hip.add(upper);upper.add(lower);lower.add(foot);bones.push(upper,lower,foot)}const skirt=new Bone();skirt.name='Skirt_F_L_01_Sp';skirt.position.set(.1,0,.025);hip.add(skirt);bones.push(skirt);const hair=new Bone();hair.name='Hair_F_L_01_Sp';hip.add(hair);bones.push(hair);const points=[];for(let row=0;row<5;row++)for(let col=0;col<4;col++)points.push(.065+col*.02,.59+row*.05,.024);const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(points,3));const weights=[],indices=[];for(let i=0;i<points.length/3;i++){weights.push(1,0,0,0);indices.push(7,0,0,0)}g.setAttribute('skinWeight',new Float32BufferAttribute(weights,4));g.setAttribute('skinIndex',new Uint16BufferAttribute(indices,4));const mesh=new SkinnedMesh(g,new MeshBasicMaterial());mesh.name='Body_Mesh';root.add(mesh);root.updateMatrixWorld(true);mesh.bind(new Skeleton(bones));return{root,hip,skirt,hair,bones,mesh,solver:new StableGarmentContacts(root)}}
test('actual weighted garment samples respond to body-capsule penetration without moving root or legs',()=>{const f=fixture(),positions=f.bones.map(b=>b.position.toArray()),scales=f.bones.map(b=>b.scale.toArray()),legs=f.bones.slice(0,7).map(b=>b.quaternion.toArray());const s=f.solver.solve();assert.equal(s.supported,true);assert.ok(s.contacts>0);assert.ok(s.afterDepth<s.beforeDepth*.9);assert.ok(s.maxRotation<=.551);assert.deepEqual(f.bones.map(b=>b.position.toArray()),positions);assert.deepEqual(f.bones.map(b=>b.scale.toArray()),scales);assert.deepEqual(f.bones.slice(0,7).map(b=>b.quaternion.toArray()),legs);assert.deepEqual(f.hair.quaternion.toArray(),[0,0,0,1])});
test('600 repeated solves on an unchanged pose have zero accumulated drift or jitter',()=>{const f=fixture();f.solver.solve();const first=f.skirt.quaternion.toArray();for(let i=0;i<600;i++){f.solver.solve();assert.deepEqual(f.skirt.quaternion.toArray(),first)}f.solver.restore();assert.deepEqual(f.skirt.quaternion.toArray(),[0,0,0,1])});
test('turning contacts off restores the exact base and preserves authored/native transforms',()=>{const f=fixture();f.skirt.quaternion.set(.001,.02,.03,.999349789);const base=f.skirt.quaternion.toArray();f.solver.solve();f.solver.solve(false);assert.deepEqual(f.skirt.quaternion.toArray(),base);for(let i=0;i<5;i++){f.solver.solve();f.solver.restore();assert.deepEqual(f.skirt.quaternion.toArray(),base)}});
test('a fresh external writer is not overwritten by stale contact restoration',()=>{const f=fixture();f.solver.solve();f.skirt.quaternion.setFromAxisAngle(new Vector3(0,1,0),.4);const fresh=f.skirt.quaternion.toArray();f.solver.restore();assert.deepEqual(f.skirt.quaternion.toArray(),fresh)});
test('custom-pose mode leaves manually posed arms untouched',()=>{const f=fixture();for(const side of ['L','R']){const arm=new Bone(),fore=new Bone(),hand=new Bone();arm.name='Arm_'+side;fore.name='Forearm_'+side;hand.name='Hand_'+side;f.hip.add(arm);arm.add(fore);fore.add(hand);arm.position.set(side==='L'?.2:-.2,.3,0);fore.position.y=-.2;hand.position.y=-.2}const solver=new StableGarmentContacts(f.root),arms=f.bones.map(b=>b.quaternion.toArray());solver.solve(true,false);assert.deepEqual(f.bones.slice(0,7).map(b=>b.quaternion.toArray()),arms.slice(0,7))});
test('unsupported or absent humanoid/garment rig is an inert capability, not an invented skeleton',()=>{const root=new Group(),bone=new Bone();bone.name='Tentacle';root.add(bone);const solver=new StableGarmentContacts(root),old=bone.quaternion.toArray();assert.equal(solver.solve().supported,false);assert.deepEqual(bone.quaternion.toArray(),old);solver.dispose()});
test('a rotated/scaled actor keeps finite bounded contacts and original segment lengths',()=>{const f=fixture(),parent=new Group();parent.add(f.root);parent.rotation.set(.1,.4,.1);parent.scale.setScalar(1.5);f.root.updateWorldMatrix(true,true);const before=f.bones.map(b=>b.position.length());for(let i=0;i<60;i++){const state=f.solver.solve();assert.ok(Number.isFinite(state.afterDepth));assert.ok(state.maxRotation<=.551)}assert.deepEqual(f.bones.map(b=>b.position.length()),before)});

test('independent build rollback cannot be overridden by a browser preference and does not remove studio',()=>{const source=fs.readFileSync('src/viewer/index.ts','utf8'),build=fs.readFileSync('scripts/build-deployment.mjs','utf8');assert.match(source,/garmentContactsAvailable = import\.meta\.env\.VITE_MAGIUS_GARMENT_CONTACTS !== 'off'/);assert.match(source,/Boolean\(value&&garmentContactsAvailable\)/);assert.match(source,/poseGravity\.setEnabled\(gravity\.checked&&garmentContactsAvailable\)/);assert.match(build,/VITE_MAGIUS_GARMENT_CONTACTS: garmentContacts/);assert.match(source,/mountPerformanceStudio/);assert.match(source,/new PerformanceRecorder/);assert.match(build,/garmentContacts, garmentContactPolicy/)});
