import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {test} from 'node:test';import vm from 'node:vm';import zlib from 'node:zlib';
const root=path.resolve(process.env.NATIVE_TEST_ROOT??path.dirname(fileURLToPath(import.meta.url))), overlay=process.env.NATIVE_TEST_OVERLAY;
const require=createRequire(path.join(root,'package.json')),ts=require('typescript'),THREE=require('three');
const actual=rel=>overlay&&fs.existsSync(path.join(overlay,rel))?path.join(overlay,rel):path.join(root,rel),read=rel=>fs.readFileSync(actual(rel),'utf8');
const base='magia-exedra-character-three/',model=base+'models/chara_101002_battle_unit/';
function compile(source,imports={}){const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};vm.runInNewContext(output,{exports,require:n=>{if(n in imports)return imports[n];throw Error('Unexpected import '+n)},structuredClone,Object,Map,Set,JSON});return exports}
const scope=compile(read(base+'nativeMaterialScope.ts'),{three:THREE});
function loader(){const text=read(base+'loader.ts'),tree=ts.createSourceFile('loader.ts',text,ts.ScriptTarget.Latest,true);const fn=tree.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='loadNativeCharacterMaterialInput');assert.ok(fn);const src=ts.transpileModule(fn.getText(tree),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};vm.runInNewContext(src,{exports,fetchAndTryDecompressGzip:async url=>{let b=fs.readFileSync(fileURLToPath(url));if(b[0]===31&&b[1]===139)b=zlib.gunzipSync(b);return new Blob([b])},createNativeMaterialScope:scope.createNativeMaterialScope,throwIfCharacterLoadAborted:()=>{}});return exports.loadNativeCharacterMaterialInput}
function files(){const names=new Set(fs.readdirSync(path.join(root,model)));if(overlay&&fs.existsSync(path.join(overlay,model)))for(const n of fs.readdirSync(path.join(overlay,model)))names.add(n);return Object.fromEntries([...names].map(n=>[model+n,new URL('file:///'+actual(model+n).replaceAll('\\','/')).href]))}
test('bundler includes model-local binding contracts as asset URLs',()=>{assert.match(read('src/viewer/character.ts'),/models\/\*\*\/model-binding-contract\.json\*/)});
test('sealed 101002 contract matches native packet mesh slot and identity',()=>{const expected=JSON.parse(read(model+'model-binding-contract.json'));const packet=JSON.parse(read(model+'runtime-material-channel.json'));const result=scope.createNativeMaterialScope(packet,expected);assert.equal(result.data.characterId,101002);assert.equal(result.data.meshes.length,expected.meshBindings.length);assert.ok(expected.meshBindings.length>0)});
test('actual native input loader resolves every companion and channel from packaged siblings',async()=>{const result=await loader()(files());assert.equal(result.packet.characterId,101002);assert.ok(result.channels.byteLength>0);assert.equal(Object.keys(result.cornerIndices).length,result.packet.meshes.length);assert.equal(Object.keys(result.textureUrls).length,Object.keys(result.packet.textures).length);assert.ok(result.bakedNormalBuffer.byteLength>0)});
test('missing contract stays a precise error instead of bypassing native identity',async()=>{const f=files();delete f[model+'model-binding-contract.json'];await assert.rejects(()=>loader()(f),/Exact native companion missing: model-binding-contract.json/)});
