import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';
import assert from 'node:assert/strict';import test from 'node:test';
import {createRequire} from 'node:module';import {fileURLToPath,pathToFileURL} from 'node:url';
const repo=path.dirname(fileURLToPath(import.meta.url));
const require=createRequire(path.join(repo,'package.json')),THREE=require('three'),ts=require('typescript');
const base='magia-exedra-character-three/';
const read=relative=>fs.readFileSync(path.join(repo,base,relative),'utf8');
const doc=JSON.parse(read('official-material-profiles.json'));
function module(source,imports){const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true},reportDiagnostics:true});assert.deepEqual(compiled.diagnostics,[]);const m={exports:{}};Function('exports','require','module',compiled.outputText)(m.exports,id=>{if(Object.hasOwn(imports,id))return imports[id];throw Error('Unexpected dependency '+id);},m);return m.exports;}
const profiles=module(read('materialProfile.ts'),{'./official-material-profiles.json?url':'unfetched-owned-profile'});
await profiles.loadOfficialMaterialProfiles(doc);
const name='mt_chara_109801_hair_space',slot=profiles.getOfficialMaterialProfile(name);
const user=module(read('shaders/userdata.ts'),{three:THREE});
const loaded=[];
const textureModule={async loadTexture(url,properties){const texture=new THREE.Texture();texture.name=url;Object.assign(texture,properties);loaded.push(texture);return texture;},ApplyOfficialCharacterSurfaceSampling(texture){return {name:texture.name};},ApplyOfficialSpecularGradientSampling(){}};
class Uniforms {constructor(shader){this.shader=shader;}loadGlobalOptions(){} setValue(k,v){this.shader.uniforms[k]={value:v};}getValue(k){return this.shader.uniforms[k]?.value;}}
const general=module(read('shaders/general.ts'),{three:THREE,'.':user,'../texture':textureModule,'../materialProfile':profiles,'./stylization':{ToonStylizationUniforms:Uniforms,injectToonStylization(){}},'./gem':{setOfficialMaterialProfileUniforms(){}},'./perspective':{injectCharacterPerspectiveCancellation(){}},'./depthRim':{injectReDriveDepthRimShader(){}},'../nativeMaterialScope':{applyNativeSlotShaderBindings(){}}});
const cosmic=module(read('shaders/namae.ts'),{three:THREE,'../texture':textureModule,'.':user,'../models/chara_113401_model/cloud_noise_tex.png':'cloud_noise_tex'});
// Execute the exact source branch, not a reimplementation of its predicates.
async function branch(profile,variant='candidate',factory=general.createGeneralMaterial,omit=[]){
 const source=read('loader.ts',variant),start=source.indexOf('                        let customBaseMaterial = material'),end=source.indexOf('                        const cosmicTextureName =',start);
 assert.ok(start>0&&end>start);const body=ts.transpileModule(source.slice(start,end)+'\nreturn customBaseMaterial',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
 const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
 const fn=new AsyncFunction('material','standardReDriveCosmic','slotProfile','findOfficialTextureUrl','hasOfficialNullCosmicBaseMap','createGeneralMaterial','inferMaterialFeatures','specularGradientMap','characterPerspectiveReference','textures','extendMaterialWithOfficialGem','texturePathUrl',body);
 return fn(new THREE.MeshStandardMaterial(),true,profile,v=>v&&!omit.includes(v)?v:undefined,profiles.hasOfficialNullCosmicBaseMap,factory,()=>({}),undefined,undefined,[],async()=>({resources:{textures:[]}}),{});
}
let material,projected;
test('03 candidate branch constructs an untextured native base and exact ControlMap',async()=>{material=await branch(slot);assert.equal(material.map,null);assert.deepEqual(material.color.toArray(),slot.cosmic.baseColor.slice(0,3));assert.equal(material.opacity,slot.cosmic.baseColor[3]);assert.deepEqual(loaded.map(x=>x.name),['RDToon_ctrl_template']);});
test('04 real projected Cosmic constructor retains authored data without a placeholder BaseMap',async()=>{projected=await cosmic.createOfficialCustomCharacterMaterial({profile:cosmic.createOfficialReDriveCosmicShaderProfile(slot),materialProfile:slot,baseMaterial:material,dedicatedBaseMaterial:true,cosmicMap:slot.cosmic.texture});assert.equal(projected.material.map,null);assert.equal(projected.resources.kind,'redrive-cosmic');assert.equal(projected.resources.cosmicTexture.name,slot.cosmic.texture);assert.equal(projected.material.userData.officialCustomCharacterShader.cosmicTexture,'chara_109801_hair_inside_color');assert.equal(projected.material.userData.officialCustomCharacterShader.overlay,true);assert.deepEqual(projected.material.userData.officialCustomCharacterShader.cosmicScroll,slot.cosmic.scroll);});
test('05 compile hook keeps control UV0 with no BaseMap and guards screen-map sampling',()=>{const shader={uniforms:{},defines:{},vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader};projected.material.onBeforeCompile(shader,{});assert.equal(shader.defines.USE_UV,true);assert.equal(shader.defines.HAS_CTRL,true);assert.equal(shader.uniforms.tCtrl.value.name,'RDToon_ctrl_template');assert.doesNotMatch(shader.fragmentShader,/vMapUv/);assert.match(shader.fragmentShader,/#ifdef USE_MAP\s+officialCosmicScreenBase = texture2D\(/);assert.match(shader.fragmentShader,/officialCosmicBase \+ officialCosmicMap/);});
test('06 missing named BaseMap still fails rather than borrowing another texture',async()=>{const profile=structuredClone(slot);profile.cosmic.baseTexture='missing_native_base';await assert.rejects(branch(profile,'candidate',general.createGeneralMaterial,['missing_native_base']),/BaseMap is missing/);});
test('07 missing external ControlMap fails closed',async()=>{await assert.rejects(branch(slot,'candidate',general.createGeneralMaterial,['RDToon_ctrl_template']),/Serialized Cosmic ControlMap is missing/);});
test('08 missing or contradictory NULL provenance fails closed',async()=>{for(const change of [p=>delete p.cosmic.nullBaseMap,p=>p.cosmic.nullBaseMap.pathId='42',p=>p.cosmic.nullBaseMap.shaderDefault='black',p=>p.cosmic.nullBaseMap.materialName='different_material',p=>p.cosmic.nullBaseMap.status='UNRESOLVED',p=>p.cosmic.isScreenBaseMap=true]){const p=structuredClone(slot);change(p);await assert.rejects(branch(p),/BaseMap is missing/);}});
test('09 direct constructor rejects an unproven null-map request',async()=>{const p=structuredClone(slot);delete p.cosmic.nullBaseMap;await assert.rejects(general.createGeneralMaterial({colorMap:'',officialNullBaseMap:p}),/Invalid serialized NULL/);});
test('10 all 14 adjacent Cosmic profiles retain exact slot URL selection',async()=>{const rows=Object.entries(doc.materials).filter(([n,p])=>n!==name&&p.cosmic?.enabled);assert.equal(rows.length,14);for(const [n,p] of rows){let options;await branch({...p,name:n},'candidate',async o=>{options=o;return {material:new THREE.MeshStandardMaterial(),textures:[]};});assert.equal(options.colorMap,p.cosmic.baseTexture);assert.equal(options.ctrlMap,p.cosmic.controlTexture??undefined);assert.equal(options.officialNullBaseMap,undefined);}});
test('13 opaque NULL route does not weaken alpha ShadowTex requirements',async()=>{const p=structuredClone(profiles.getOfficialMaterialProfile('mt_chara_100805_hair_alpha'));await assert.rejects(branch(p,'candidate',general.createGeneralMaterial,[p.cosmic.shadowTexture]),/ShadowTex alpha is missing/);});
test('14 native NULL ShadowTex binds its distinct serialized ShadowColor',()=>{const expected=[0.48737624287605286,0.53910893201828,0.550000011920929];assert.deepEqual(expected,[0.48737624287605286,0.53910893201828,0.550000011920929]);assert.notDeepEqual(expected,slot.cosmic.baseColor.slice(0,3));assert.deepEqual(slot.cosmic.nullBaseMap.shadow.color,[...expected,1]);const shader={uniforms:{},defines:{},vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader};projected.material.onBeforeCompile(shader,{});assert.deepEqual(shader.uniforms.rdNativeShadowColor.value.toArray(),expected);assert.match(shader.fragmentShader,/vec3 rdToonShadowColor = rdNativeShadowColor;/);assert.doesNotMatch(shader.fragmentShader,/vec3 rdToonShadowColor = diffuseColor.rgb;/);assert.deepEqual(material.color.toArray(),slot.cosmic.baseColor.slice(0,3));});
test('15 absent or nonfinite native ShadowColor is rejected, not copied from BaseColor',async()=>{for(const change of [p=>delete p.cosmic.nullBaseMap.shadow,p=>p.cosmic.nullBaseMap.shadow.color[0]=NaN,p=>p.cosmic.nullBaseMap.shadow.color[0]=Infinity,p=>p.cosmic.nullBaseMap.shadow.color[0]=-Infinity]){const p=structuredClone(slot);change(p);await assert.rejects(branch(p),/BaseMap is missing/);}});
