import fs from 'node:fs'; import path from 'node:path'; import zlib from 'node:zlib';
import test from 'node:test'; import assert from 'node:assert/strict';
import {createRequire} from 'node:module'; import {fileURLToPath,pathToFileURL} from 'node:url';
// Portable constructor/sampler/loader regression. Texture transport is mocked;
// native pixel equivalence and WebGL drawing are separate integration gates.
const repo=path.dirname(fileURLToPath(import.meta.url)),base='magia-exedra-character-three/';
const require=createRequire(path.join(repo,'package.json')),THREE=require('three'),ts=require('typescript');
const read=rel=>fs.readFileSync(path.join(repo,base,rel),'utf8');
const doc=JSON.parse(read('official-material-profiles.json'));
const native={"m_SavedProperties":{"m_Floats":[["_1stFresnelMaskNoiseIntensity",2.5299999713897705],["_1stFresnelMaskNoiseSpeed",8.0],["_1stFresnelMaskNoiseTilling",0.05999999865889549],["_1stFresnelStep",0.2849999964237213],["_2ndFresnelMaskNoiseIntensity",1.0],["_2ndFresnelMaskNoiseSpeed",-0.20000000298023224],["_2ndFresnelMaskNoiseTillingLength",3.0],["_2ndFresnelMaskNoiseTillingRadial",0.5],["_2ndFresnellStep",0.0],["_BaseSpeed",4.0],["_BaseTilling",0.07000000029802322],["_HighlightIntensity",3.0],["_HighlightSpeed",8.0],["_HighlightTilling",0.10000000149011612],["_QueueControl",0.0],["_QueueOffset",0.0]],"m_Colors":[["_1stColor",{"r":0.9499998092651367,"g":0.0,"b":1.0,"a":0.0}],["_1stFresnelMaskNoiseSheet",{"r":2.0,"g":2.0,"b":0.0,"a":0.0}],["_2ndColor",{"r":0.0,"g":0.0,"b":0.0,"a":0.0}],["_BaseSheet",{"r":4.0,"g":4.0,"b":0.0,"a":0.0}],["_HighlightSheet",{"r":2.0,"g":2.0,"b":0.0,"a":0.0}]]}};
const pixels=[{"property":"_1stFresnelMaskNoise","name":"chara_113801_weapon_a_orb_1stfresnel_noise","width":256,"height":256,"m_ColorSpace":0,"pathIdDecimal":"7980463908955212881"},{"property":"_2ndFresnelMaskNoise","name":"chara_113801_weapon_a_orb_2ndfresnel_noise","width":128,"height":128,"m_ColorSpace":0,"pathIdDecimal":"-4656170475755678125"},{"property":"_BaseMap","name":"chara_113801_weapon_a_orb_color","width":512,"height":512,"m_ColorSpace":1,"pathIdDecimal":"6362689713899864983"},{"property":"_HighlightMap","name":"chara_113801_weapon_a_orb_highlight","width":256,"height":256,"m_ColorSpace":0,"pathIdDecimal":"-5716736887467862487"}];
function module(source,imports){const c=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true},reportDiagnostics:true});assert.deepEqual(c.diagnostics,[]);const m={exports:{}};Function('exports','require','module',c.outputText)(m.exports,id=>{if(Object.hasOwn(imports,id))return imports[id];throw Error('Unexpected import '+id);},m);return m.exports;}
const profiles=module(read('materialProfile.ts'),{'./official-material-profiles.json?url':'unused-profile-url'});await profiles.loadOfficialMaterialProfiles(doc);
const user=module(read('shaders/userdata.ts'),{three:THREE});
const sampling=module(read('texture.ts'),{three:THREE,'./shaders/face_ctrl_base.png?url':'fixture-face-base','./shaders/face_ctrl_nose.png?url':'fixture-face-nose','./models/chara_100202_battle_unit/chara_100202_face_ctrl.png?url':'fixture-face-ctrl','./loadingProgress.ts':{},'./materialProfile':profiles,'./officialTextureContainer':{getOfficialCompressedTextureState(){return undefined;}},'./renderer':{renderer:undefined}});
let omit='',failAt='',loaded=[],disposed=[];
const textureModule={async loadTexture(url){if(url===failAt)throw Error('Exact fixture fetch failure '+url);const row=pixels.find(x=>x.name===url);assert.ok(row,'Texture must be a recovered native input');const t=new THREE.Texture({width:row.width,height:row.height});t.name=row.name;t.addEventListener('dispose',()=>disposed.push(row.name));loaded.push(t);return t;},ApplyOfficialCharacterSurfaceSampling:sampling.ApplyOfficialCharacterSurfaceSampling};
const akuma=fs.existsSync(path.join(repo,base,'shaders/akumaWeapon.ts'))?module(read('shaders/akumaWeapon.ts'),{three:THREE,'../texture':textureModule,'./userdata':user}):{};
const imports={three:THREE,'../texture':textureModule,'.':user,'../models/chara_113401_model/cloud_noise_tex.png':'cloud_noise_tex','./akumaWeapon':akuma};
const current=module(read('shaders/namae.ts'),imports);
const name='mt_chara_113801_weapon_a_orb',profile=profiles.getOfficialMaterialProfile(name);
const resolver=n=>n===omit?undefined:n;
async function create(p=profile.customShader){return current.createOfficialCustomCharacterMaterial({profile:p,materialProfile:profile,resolveTexture:resolver});}
let result;
test('04 all 16 scalars, 5 vectors and four PPtrs survive without generic substitutes',()=>{const p=profile.customShader.akumaWeapon;assert.deepEqual(p.floats,Object.fromEntries(native.m_SavedProperties.m_Floats));for(const [k,v]of native.m_SavedProperties.m_Colors)assert.deepEqual(p.colors[k],[v.r,v.g,v.b,v.a]);assert.deepEqual(Object.keys(p.textures).sort(),['_1stFresnelMaskNoise','_2ndFresnelMaskNoise','_BaseMap','_HighlightMap'].sort());for(const x of pixels){assert.equal(p.textures[x.property].pathId,x.pathIdDecimal);assert.equal(p.textures[x.property].name,x.name);}assert.equal(p.source.materialPathID,'-6718132490086435673');});
test('06 constructor binds four exact texture identities with mocked transport',async()=>{loaded=[];result=await create();assert.equal(result.resources.kind,'akuma-weapon');assert.equal(result.material.type,'ShaderMaterial');assert.equal(result.textures.length,4);assert.equal(loaded.length,4);assert.deepEqual(loaded.map(t=>t.name),['_2ndFresnelMaskNoise','_BaseMap','_1stFresnelMaskNoise','_HighlightMap'].map(k=>profile.customShader.akumaWeapon.textures[k].name));for(const t of loaded){const row=pixels.find(x=>x.name===t.name);assert.equal(t.image.width,row.width);assert.equal(t.image.height,row.height);}});
test('07 exact serialized sampler is applied independently to all four inputs',()=>{for(const t of result.textures){const row=pixels.find(x=>x.name===t.name);assert.equal(t.wrapS,THREE.RepeatWrapping);assert.equal(t.wrapT,THREE.RepeatWrapping);assert.equal(t.magFilter,THREE.LinearFilter);assert.equal(t.minFilter,THREE.LinearMipmapNearestFilter);assert.equal(t.anisotropy,1);assert.equal(t.colorSpace,row.m_ColorSpace===1?THREE.SRGBColorSpace:THREE.NoColorSpace);assert.equal(t.generateMipmaps,true);}});
test('08 pass remains opaque depth-writing front-face, no invented outline',()=>{const m=result.material;assert.equal(m.transparent,false);assert.equal(m.depthWrite,true);assert.equal(m.depthFunc,THREE.LessEqualDepth);assert.equal(m.side,THREE.FrontSide);assert.equal(m.blending,THREE.NoBlending);assert.equal(m.alphaToCoverage,true);assert.equal(profile.outline.enabled,false);assert.equal(m.userData.officialCustomCharacterShader.outlinePass,false);});
test('09 runtime uses current target viewport, signed origin projection and camera FOV',()=>{const renderer={getRenderTarget:()=>({width:800,height:400,samples:4}),getContext:()=>({getContextAttributes:()=>({antialias:false})}),getDrawingBufferSize:v=>v.set(200,100)};const camera=new THREE.PerspectiveCamera(35,2,.1,100);camera.zoom=2;result.material.stencilWrite=true;result.material.onBeforeRender(renderer,{},camera);assert.equal(result.material.stencilWrite,false);const u=result.material.uniforms;assert.deepEqual(u.uAkumaViewport.value.toArray(),[800,400]);assert.deepEqual(u.uAkumaAspect.value.toArray(),[.5,1]);assert.equal(u.uAkumaFov.value,35);assert.equal(u.uAkumaAlphaToMask.value,1);assert.ok(u.uAkumaTime.value>0);assert.match(result.material.vertexShader,/originView\.z \* uAkumaFov \* 0\.05/);assert.doesNotMatch(result.material.vertexShader,/FacePosition|headBone|abs\(originView.z\)/);const ortho=new THREE.OrthographicCamera(-2,2,3,-3,.1,100);ortho.zoom=2;result.material.onBeforeRender(renderer,{},ortho);assert.equal(u.uAkumaOrtho.value,1);assert.equal(u.uAkumaOrthoHalfHeight.value,1.5);});
test('10 missing named texture fails before any partial loads',async()=>{loaded=[];omit=pixels[1].name;await assert.rejects(create(),/Missing Akuma texture _2ndFresnelMaskNoise/);assert.equal(loaded.length,0);omit='';});
test('11 texture fetch failure disposes already-created exact inputs',async()=>{loaded=[];disposed=[];failAt=profile.customShader.akumaWeapon.textures._1stFresnelMaskNoise.name;await assert.rejects(create(),/Exact fixture fetch failure/);assert.equal(loaded.length,2);assert.deepEqual(disposed,loaded.map(t=>t.name));failAt='';});
test('12 missing/nonfinite native scalar and missing payload stay fail-closed',async()=>{for(const change of[p=>delete p.akumaWeapon,p=>delete p.akumaWeapon.floats._BaseSpeed,p=>p.akumaWeapon.floats._BaseSpeed=NaN,p=>p.akumaWeapon.colors._BaseSheet[0]=0]){const p=structuredClone(profile.customShader);change(p);await assert.rejects(create(p),/Missing|Invalid/);}});
test('13 exact mixed-slot loader call passes stable texture resolver to factory',async()=>{const src=read('loader.ts'),start=src.indexOf('                        const result = await createOfficialCustomCharacterMaterial({',src.indexOf('                    for (const customSlot of customShaderSlots)')),end=src.indexOf('                        customMaterialOverrides.set(',start);assert.ok(start>0&&end>start);const body=ts.transpileModule(src.slice(start,end)+'\nreturn result',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;const keys=['createOfficialCustomCharacterMaterial','customProfile','slotProfile','customBaseMaterial','standardReDriveCosmic','findOfficialTextureUrl','cosmicTextureName','cosmicNoiseTextureName','getOfficialTextureSamplerProfile','cosmicReference'];const fn=new (Object.getPrototypeOf(async()=>{}).constructor)(...keys,body);const m=await fn(current.createOfficialCustomCharacterMaterial,profile.customShader,profile,new THREE.MeshStandardMaterial(),false,resolver,null,null,profiles.getOfficialTextureSamplerProfile,undefined);assert.equal(m.resources.kind,'akuma-weapon');m.textures.forEach(t=>t.dispose());m.material.dispose();});
test('14 actual FBX restores all four Weapon slots and preserves the other three',async()=>{const {FBXLoader}=await import(pathToFileURL(repo+'/node_modules/three/examples/jsm/loaders/FBXLoader.js'));const esm=await import(pathToFileURL(repo+'/node_modules/three/build/three.module.js'));const prior=esm.TextureLoader.prototype.load;esm.TextureLoader.prototype.load=()=>new esm.Texture();globalThis.window={URL:{createObjectURL(){throw Error('unexpected embedded payload');}}};try{const b=zlib.gunzipSync(fs.readFileSync(repo+'/'+base+'models/chara_113801_battle_unit/VisualRoot.fbx.gz'));const obj=new FBXLoader().parse(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');const mesh=obj.getObjectByName('Weapon_Mesh'),names=mesh.material.map(m=>m.name);assert.deepEqual(names,['mt_chara_113801_weapon_a_alpha','mt_chara_113801_weapon_a',name,'mt_chara_113801_weapon_a_OutlineOff']);const generated=module(read('submeshGroups.generated.ts'),{}),groups=module(read('submeshGroups.ts'),{three:THREE,'./submeshGroups.generated':generated});const restored=groups.restoreOfficialSubmeshGroups(mesh,113801,names.length);assert.deepEqual(restored.counts,[108,4476,1200,276]);assert.deepEqual(mesh.geometry.groups.map(g=>g.count),[108,4476,1200,276]);assert.equal(restored.drawCount,6060);assert.equal(profile.customShader.akumaWeapon.source.materialPathID,'-6718132490086435673');}finally{esm.TextureLoader.prototype.load=prior;}});
test('15 unknown custom shader still throws; name route contains no character-ID special case',async()=>{await assert.rejects(create({...profile.customShader,name:'Creative/Character/OtherUnsupported'}),/Unsupported official character shader/);assert.equal(current.supportsOfficialCustomCharacterShader(profile.customShader),true);assert.doesNotMatch(read('shaders/akumaWeapon.ts'),/113801|Weapon_Mesh|mt_chara_/);});

test('16 adjacent 109801 explicit Cosmic NULL base remains enabled',()=>{assert.ok(profiles.hasOfficialNullCosmicBaseMap(profiles.getOfficialMaterialProfile('mt_chara_109801_hair_space')));});
