import assert from 'node:assert/strict'
import test from 'node:test'
import {Group,Bone,Mesh,BoxGeometry,MeshBasicMaterial,PerspectiveCamera,Vector3,Quaternion} from 'three'
import {PerformanceTimeline,emptyPerformanceDocument} from './src/viewer/performanceEditor/timeline.ts'
import {PerformanceEditorRuntime} from './src/viewer/performanceEditor/runtime.ts'
import {PerformanceRecorder} from './src/viewer/performanceEditor/recorder.ts'
import {RecordedRig,sampleRecorded,interpolateRecorded,simplifyRecorded,captureRecordedCamera,applyRecordedCamera,insertRecordedInterval} from './src/viewer/performanceEditor/recordings.ts'
function actor(id,instance=0){const object=new Group();object.name='Model';const hip=new Bone();hip.name='Hip';const arm=new Bone();arm.name='Arm_L';arm.position.set(.2,.8,0);hip.add(arm);object.add(hip);const eye=new Bone();eye.name='Eye_L';hip.add(eye);const face=new Mesh(new BoxGeometry(),new MeshBasicMaterial());face.name='Face_Mesh';face.morphTargetDictionary={Smile:0,Blink:1};face.morphTargetInfluences=[0,0];object.add(face);let alive=true;return{object,hip,arm,eye,face,actorKey:object.uuid,resourceId:id,instance,type:'character',generation:1,label:id,current:()=>alive,remove:()=>{alive=false}}}
function fixture(){const a=actor('100101'),b=actor('102001'),actors=[a,b],camera=new PerspectiveCamera(45,1,.01,200),target=new Vector3();camera.position.set(0,1,4);camera.lookAt(target);const runtime=new PerformanceEditorRuntime({actorSource:{list:()=>[],subscribe:()=>()=>{}},channelHost:{acquire:()=>{throw Error('Recorded lanes do not steal evaluator leases')},notifyRootTransformChanged(){}},framePort:{subscribeBeforePhysics:()=>()=>{},subscribeFinalPoseBeforeCamera:()=>()=>{}}});const r=new PerformanceRecorder(runtime,{actors:()=>actors,camera:()=>({camera,target}),select(){},playback(){},releaseCamera(){}});let stamp=0;function frame(seconds,fn=()=>{}){r.restore();fn();stamp+=seconds*1000;runtime.advanceAudioOnlyFrame(stamp);r.frame()}return{a,b,actors,camera,target,r,runtime,frame,dispose:()=>{r.dispose();runtime.dispose()}}}
function record(f,a,factor=1){f.r.start(a.actorKey,['motion','expression']);f.frame(0);for(let i=1;i<=30;i++)f.frame(1/30,()=>{a.object.position.x=i/30*factor;a.arm.rotation.z=i/60;a.face.morphTargetInfluences[0]=i/30});f.r.finish()}

test('final pose recorder captures player root, custom bone transforms and independent expressions',()=>{const f=fixture();record(f,f.a);assert.equal(f.r.lanes.length,2);const motion=f.r.lanes.find(l=>l.kind==='motion'),face=f.r.lanes.find(l=>l.kind==='expression');assert.ok(motion.frames.length>=2);assert.ok(face.frames.length>=2);assert.equal(motion.target.resourceId,'100101');assert.ok(motion.frames.at(-1).values[0]>.95);assert.ok(face.bindings.some(b=>b.kind==='morphs'));f.dispose()})
test('B can be recorded while A replays on the same clock without overwriting A',()=>{const f=fixture();record(f,f.a);const first=JSON.stringify(f.r.lanes);f.r.seek(0);f.r.prepareLive(f.b.actorKey);f.r.start(f.b.actorKey,['motion','expression']);f.frame(0);let moved=false;for(let i=1;i<=30;i++){f.frame(1/30,()=>{f.b.object.position.z=i*.03});if(f.a.object.position.x>.2)moved=true}f.r.finish();assert.ok(moved);assert.equal(f.r.lanes.length,4);assert.equal(JSON.stringify(f.r.lanes.filter(l=>l.target.resourceId==='100101')),first);f.dispose()})
test('repeated seek and restore never accumulate a baked pose into a native baseline',()=>{const f=fixture();record(f,f.a);f.r.seek(.5);const expected=f.a.arm.quaternion.toArray(),x=f.a.object.position.x;for(let i=0;i<200;i++){f.r.seek(.5);assert.deepEqual(f.a.arm.quaternion.toArray(),expected);assert.equal(f.a.object.position.x,x)}f.r.stop();const baseline=f.a.object.position.toArray();for(let i=0;i<100;i++){f.frame(1/60);assert.deepEqual(f.a.object.position.toArray(),baseline)}f.dispose()})
test('raw overlay restoration preserves non-unit imported Float32 quaternions exactly',()=>{const a=actor('100101');a.arm.quaternion.set(.1,.2,.3,.927361846);const rig=new RecordedRig(a,'motion'),before=rig.capture(true);a.arm.rotation.x=1;rig.apply(before,true);assert.deepEqual(rig.capture(true),before)})
test('camera keyframes preserve optical roll, target, field of view and replay interpolation',()=>{const f=fixture();f.r.captureKey('camera');f.runtime.time=2;f.camera.position.x=2;f.camera.rotateZ(.4);f.camera.fov=55;f.r.captureKey('camera');const lane=f.r.lanes[0];f.r.seek(1);assert.ok(Math.abs(f.camera.position.x-1)<1e-6);assert.equal(f.camera.fov,50);const sample=captureRecordedCamera(f.camera,f.target);for(let i=0;i<30;i++){f.r.seek(1);assert.deepEqual(captureRecordedCamera(f.camera,f.target),sample)}assert.equal(lane.kind,'camera');f.dispose()})
test('an expression lane never overwrites body or another actor',()=>{const f=fixture();f.r.captureKey(f.a.actorKey,['expression']);f.a.object.position.x=7;f.b.face.morphTargetInfluences[0]=.6;f.r.seek(0);assert.equal(f.a.object.position.x,7);assert.equal(f.b.face.morphTargetInfluences[0],.6);f.dispose()})
test('same-name sibling model paths remain unique and foreign topology fails before mutation',()=>{const a=actor('100101'),other=new Bone();other.name='Arm_L';a.hip.add(other);const rig=new RecordedRig(a,'motion');assert.equal(new Set(rig.bindings.map(b=>b.path+':'+b.kind)).size,rig.bindings.length);a.hip.remove(other);assert.throws(()=>new RecordedRig(a,'motion',rig.bindings),/模型层级/);assert.equal(a.object.position.x,0)})
test('zero-scale authored visibility switches remain discrete and exact',()=>{const a=actor('100101'),rig=new RecordedRig(a,'motion');const x=rig.capture();a.arm.scale.set(0,0,0);const y=rig.capture(),lane={kind:'motion',bindings:rig.bindings};const half=interpolateRecorded(lane,x,y,.5);rig.apply(half);assert.deepEqual(a.arm.scale.toArray(),[1,1,1]);rig.apply(interpolateRecorded(lane,x,y,1));assert.deepEqual(a.arm.scale.toArray(),[0,0,0])})
test('malformed recorded data is rejected atomically while the existing document stays intact',()=>{const f=fixture();record(f,f.a);const before=f.runtime.exportProject(),bad=JSON.parse(before);bad.recordedLanes[0].frames[0].values[0]=NaN;assert.throws(()=>f.runtime.setDocument(bad),/非法/);assert.equal(f.runtime.exportProject(),before);const duplicate=JSON.parse(before);duplicate.recordedLanes.push(structuredClone(duplicate.recordedLanes[0]));assert.throws(()=>f.runtime.setDocument(duplicate),/轨道格式/);assert.equal(f.runtime.exportProject(),before);f.dispose()})
test('one-interval retake preserves both sides and other lanes',()=>{const f=fixture();record(f,f.a);const lane=f.r.lanes[0],incoming=structuredClone(lane);incoming.frames=[{time:.5,values:[...lane.frames[0].values]}];incoming.frames[0].values[0]=5;const merged=insertRecordedInterval(lane,incoming);assert.equal(merged.frames[0].time,lane.frames[0].time);assert.equal(merged.frames.at(-1).time,lane.frames.at(-1).time);assert.equal(sampleRecorded(merged,.5)[0],5);f.dispose()})
test('linear key data simplifies within error without inventing extra frames',()=>{const f=fixture(),rig=new RecordedRig(f.a,'motion'),lane={id:'x',kind:'motion',label:'A',target:f.a,bindings:rig.bindings,frames:[]};for(let i=0;i<=60;i++){f.a.object.position.x=i/60;lane.frames.push({time:i/60,values:rig.capture()})}const simplified=simplifyRecorded(lane);assert.equal(simplified.length,2);for(let i=0;i<=60;i++)assert.ok(Math.abs(sampleRecorded({...lane,frames:simplified},i/60)[0]-i/60)<1e-6);f.dispose()})
test('removing a bound instance cannot silently retarget its take to a duplicate model',()=>{const f=fixture();record(f,f.a);f.r.seek(.5);f.a.remove();const replacement=actor('100101');f.actors.push(replacement);f.r.frame();assert.match(f.r.error,/加载录制角色/);assert.equal(replacement.object.position.x,0);f.dispose()})
test('import explicitly rebinds a portable project to the correct model and instance',async()=>{const f=fixture();record(f,f.a);const text=f.runtime.exportProject(),g=fixture();await g.r.import(text);g.r.seek(.5);assert.ok(Math.abs(g.a.object.position.x-.5)<.04);assert.equal(g.b.object.position.x,0);f.dispose();g.dispose()})
test('recording cancellation restores the complete previous project',()=>{const f=fixture();record(f,f.a);const old=f.runtime.exportProject();f.r.seek(0);f.r.start(f.b.actorKey,['motion']);f.frame(0);f.frame(.1,()=>{f.b.object.position.x=1});f.r.cancel();assert.equal(f.runtime.exportProject(),old);assert.equal(f.r.recording,false);f.dispose()})
test('recording project edits have bounded undo and redo including mute/delete',()=>{const f=fixture();record(f,f.a);const id=f.r.lanes[0].id;f.r.mute(id);assert.equal(f.r.lanes[0].muted,true);f.r.undo();assert.notEqual(f.r.lanes[0].muted,true);f.r.undo(true);assert.equal(f.r.lanes[0].muted,true);f.r.remove(id);assert.equal(f.r.lanes.length,1);f.r.undo();assert.equal(f.r.lanes.length,2);f.dispose()})
test('frame clock and record playback do not deep-clone the project every frame',()=>{const f=fixture();record(f,f.a);f.r.play();Object.defineProperty(f.runtime.timeline,'value',{get(){throw Error('Large project cloned on hot path')}});assert.doesNotThrow(()=>{f.frame(0);for(let i=0;i<12;i++)f.frame(1/60)});f.dispose()})
test('legacy empty and authored/audio-only documents remain valid',()=>{const d=emptyPerformanceDocument(),timeline=new PerformanceTimeline(d);assert.deepEqual(timeline.value,d);assert.deepEqual(timeline.recordedLanes,[]);assert.deepEqual(PerformanceTimeline.deserialize(timeline.serialize()).value,d)})

test('editing a sampled camera frame starts at that displayed view, not the underlying live camera',()=>{const f=fixture();f.r.captureKey('camera');f.runtime.time=2;f.camera.position.x=4;f.r.captureKey('camera');f.r.seek(1);const before=captureRecordedCamera(f.camera,f.target);f.r.prepareLive('camera');assert.deepEqual(captureRecordedCamera(f.camera,f.target),before);f.frame(1/60);assert.deepEqual(captureRecordedCamera(f.camera,f.target),before);f.dispose()})
test('long recordings simplify in bounded chunks without dropping the last endpoint',()=>{const a=actor('100101'),rig=new RecordedRig(a,'motion'),lane={id:'long',kind:'motion',label:'A',target:a,bindings:rig.bindings,frames:[]};for(let i=0;i<=1500;i++){a.object.position.x=i/1000;lane.frames.push({time:i/30,values:rig.capture()})}const frames=simplifyRecorded(lane);assert.equal(frames[0].time,0);assert.equal(frames.at(-1).time,50);for(let i=0;i<1500;i+=37)assert.ok(Math.abs(sampleRecorded({...lane,frames},i/30)[0]-i/1000)<1e-6)})

test('finishing a take releases live TPS input and re-editing aligns the controller with the sampled root',()=>{const f=fixture();let stops=0,alignments=0;f.r.host.stopInput=()=>stops++;f.r.host.syncRoot=actor=>{assert.equal(actor.actorKey,f.a.actorKey);alignments++};record(f,f.a);assert.equal(stops,1);f.r.seek(.5);f.r.prepareLive(f.a.actorKey,['motion']);assert.equal(alignments,1);f.dispose()});

test('controller root reset cannot replace the displayed pose used as the editing baseline',()=>{const f=fixture();record(f,f.a);f.r.seek(.5);const before=f.a.arm.quaternion.toArray();f.r.host.syncRoot=()=>f.a.arm.quaternion.identity();let adopted=false;f.r.host.adoptPose=()=>{adopted=true;assert.deepEqual(f.a.arm.quaternion.toArray(),before)};f.r.prepareLive(f.a.actorKey,['motion']);assert.ok(adopted);assert.deepEqual(f.a.arm.quaternion.toArray(),before);f.dispose()});
