import assert from 'node:assert/strict'
import test from 'node:test'
import * as T from 'three'
import {PlacementHistory,StructurePoseTarget,groupedPoseParts,structuralNodes,nodePath,captureModelLocal,makeSavedPose,resolveSavedPose,validateSavedPose,savePoseLibrary,readPoseLibrary,deleteSavedPose,readLocal} from './src/viewer/poseWorkspace.ts'
import {DirectPoseHistory} from './src/viewer/directPoseTools.ts'
function rig(){const actor=new T.Group();const bone=(name,parent=actor)=>{const b=new T.Bone();b.name=name;b.position.set(.1,.2,.1);parent.add(b);return b};const hand=bone('Hand_L'),finger=bone('Index_L_01',hand),finger2=bone('Thumb_L_01',hand),end=bone('Index_L_End',finger),cloth=bone('Skirt_A_01'),head=bone('Head');const mesh=new T.Mesh(new T.BoxGeometry(),new T.MeshBasicMaterial());mesh.name='Body_Mesh';actor.add(mesh);const outline=mesh.clone();outline.name='Body_Mesh:official-outline:0';actor.add(outline);actor.updateMatrixWorld(true);return{actor,hand,finger,finger2,end,cloth,head,mesh,outline}}
const store=()=>{const data=new Map();return{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)}}
test('logical groups are disjoint, real bones only, and removed free UI is not a fourth group',()=>{const r=rig(),a=groupedPoseParts(r.actor,'primary'),b=groupedPoseParts(r.actor,'hands'),c=groupedPoseParts(r.actor,'more');assert.ok(a.some(p=>p.bone===r.hand));assert.deepEqual(new Set(b.map(p=>p.bone)),new Set([r.finger,r.finger2]));assert.ok(c.some(p=>p.bone===r.cloth));assert.ok(c.every(p=>!a.some(x=>x.bone===p.bone)&&!b.some(x=>x.bone===p.bone)));assert.deepEqual(groupedPoseParts(r.actor,'free'),[]);assert.ok([...a,...b,...c].every(p=>p.bone!==r.mesh&&p.bone!==r.end&&p.bone!==r.outline));assert.ok(structuralNodes(r.actor).includes(r.mesh),'model-local save/import still retains structural channels')})
test('placement reset is itself undoable, preserves quaternion and scale, and redo is invalidated by a new gesture',()=>{const o=new T.Group();o.position.set(1,2,3);const h=new PlacementHistory(o),initial=readLocal(o);h.begin();o.position.x=7;o.rotation.y=.7;o.scale.setScalar(2);h.finish();const moved=readLocal(o);h.reset();assert.deepEqual(readLocal(o),initial);assert.ok(h.undo());assert.deepEqual(readLocal(o),moved);assert.ok(h.undo(true));assert.deepEqual(readLocal(o),initial);h.undo();h.begin();o.position.y=6;h.finish();assert.equal(h.canRedo,false)})
test('unchanged gestures do not create history and completed gestures are bounded',()=>{const o=new T.Group(),h=new PlacementHistory(o);h.begin();h.finish();assert.equal(h.canUndo,false);for(let i=0;i<60;i++){h.begin();o.position.x++;h.finish()}let count=0;while(h.undo())count++;assert.equal(count,40)})
test('full pose history retains arbitrary position, quaternion and scale channels across reset',()=>{const h=new DirectPoseHistory(),a=new Map([['q',[0,0,0,1]],['p',[1,2,3]],['s',[1,1,1]]]),b=new Map([['q',[0,.6,0,.8]],['p',[1,5,3]],['s',[2,1,1]]]);h.begin(a);h.finish(b);assert.deepEqual(h.undo(b),a);assert.deepEqual(h.redo(a),b);h.begin(b);h.finish(a);assert.deepEqual(h.undo(a),b)})
for(const kind of ['bone','mesh'])test('free '+kind+' defaults to rotation-only and cannot stretch by translate',()=>{const r=rig(),node=kind==='bone'?r.finger:r.mesh,t=new StructurePoseTarget(r.actor,node,false,()=>false),initial=readLocal(node);assert.equal(t.canTranslate,false);assert.equal(t.begin('translate'),false);assert.equal(t.begin('rotate'),true);t.handle.quaternion.multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,0,1),.4));t.queue();assert.equal(t.flush().length,1);t.end();assert.deepEqual(node.position.toArray(),initial.p);assert.deepEqual(node.scale.toArray(),initial.s);assert.ok(node.quaternion.angleTo(new T.Quaternion().fromArray(initial.q))>.1)})
test('structure translation needs opt-in and respects selected root identity',()=>{const r=rig(),t=new StructurePoseTarget(r.actor,r.cloth,true,()=>false);assert.ok(t.begin('translate'));const start=r.cloth.position.clone();t.handle.position.x+=.3;t.queue();t.flush();assert.ok(Math.abs(r.cloth.position.x-start.x-.3)<1e-8);t.end();r.cloth.removeFromParent();assert.ok(t.begin('rotate'));t.queue();assert.deepEqual(t.flush(),[])})
test('leased nodes and nonfinite requests cannot be edited',()=>{const r=rig(),blocked=new StructurePoseTarget(r.actor,r.finger,true,()=>true);assert.equal(blocked.begin('rotate'),false);const t=new StructurePoseTarget(r.actor,r.finger,true,()=>false);t.begin('translate');t.handle.position.x=NaN;t.queue();assert.deepEqual(t.flush(),[])})
test('saved poses survive a new hierarchy UUID and match model-local paths',()=>{const a=rig(),baseline=captureModelLocal(a.actor);a.finger.rotation.z=.3;const pose=makeSavedPose(a.actor,'100107','Fingers',baseline),b=rig();assert.notEqual(a.finger.uuid,b.finger.uuid);const changes=resolveSavedPose(b.actor,'100107',pose,false,captureModelLocal(b.actor));const target=changes.find(x=>x.node===b.finger);assert.ok(target);assert.deepEqual(target.transform.q,a.finger.quaternion.toArray());assert.equal(pose.requiresStretch,false)})
test('wrong model, changed hierarchy, duplicate path and malformed quaternion fail before any mutation',()=>{const r=rig(),base=captureModelLocal(r.actor),pose=makeSavedPose(r.actor,'100107','p',base),before=readLocal(r.finger);assert.throws(()=>resolveSavedPose(r.actor,'100201',pose,false,base));const wrong=structuredClone(pose);wrong.nodes.pop();assert.throws(()=>resolveSavedPose(r.actor,'100107',wrong,false,base));const duplicate=structuredClone(pose);duplicate.nodes.push(duplicate.nodes[0]);assert.throws(()=>validateSavedPose(duplicate));const bad=structuredClone(pose);bad.nodes[0].transform.q=[0,0,0,0];assert.throws(()=>validateSavedPose(bad));assert.deepEqual(readLocal(r.finger),before)})
test('forged requiresStretch=false cannot import translations while safety is off',()=>{const r=rig(),base=captureModelLocal(r.actor),pose=makeSavedPose(r.actor,'100107','p',base);pose.nodes[0].transform.p[0]+=.5;pose.requiresStretch=false;assert.throws(()=>resolveSavedPose(r.actor,'100107',pose,false,base),/结构位移/);assert.equal(resolveSavedPose(r.actor,'100107',pose,true,base).length,pose.nodes.length)})
test('same-name sibling paths are unique and outside nodes are rejected',()=>{const r=rig(),a=new T.Bone(),b=new T.Bone();a.name=b.name='Same';r.actor.add(a,b);assert.notEqual(nodePath(a,r.actor),nodePath(b,r.actor));assert.throws(()=>nodePath(new T.Bone(),r.actor))})
test('library persists multiple models, replaces only same model/name and does not corrupt data on quota errors',()=>{const storage=store(),r=rig(),base=captureModelLocal(r.actor);savePoseLibrary(storage,makeSavedPose(r.actor,'100107','A',base));savePoseLibrary(storage,makeSavedPose(r.actor,'100201','A',base));assert.equal(readPoseLibrary(storage).length,2);r.finger.rotation.x=.3;savePoseLibrary(storage,makeSavedPose(r.actor,'100107','A',base));assert.equal(readPoseLibrary(storage).length,2);deleteSavedPose(storage,'100107','A');assert.equal(readPoseLibrary(storage)[0].model,'100201');assert.throws(()=>savePoseLibrary({getItem:storage.getItem,setItem(){throw Error('quota')}},makeSavedPose(r.actor,'100107','B',base)),/quota/);assert.equal(readPoseLibrary(storage).length,1)})
