import assert from 'node:assert/strict'
import test from 'node:test'
import fs from 'node:fs'
import ts from 'typescript'
import * as THREE from 'three'
import {captureModelLocal,writeLocal,readLocal} from './src/viewer/poseWorkspace.ts'
const s=fs.readFileSync(new URL('./src/viewer/index.ts',import.meta.url),'utf8'),tree=ts.createSourceFile('i.ts',s,ts.ScriptTarget.Latest,true)
const names=['poseQuaternionMatches','applyPoseEntry','restoreManualPoseOverrides','applyManualPoseOverrides','freezePoseForEditing']
const nodes=tree.statements.filter(n=>ts.isFunctionDeclaration(n)&&names.includes(n.name?.text));assert.equal(nodes.length,names.length)
const code=ts.transpileModule(nodes.map(n=>n.getText(tree)).join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText
function fixture(){const actor=new THREE.Group(),bone=new THREE.Bone();bone.name='Skirt';bone.position.y=1;bone.rotation.z=.3;actor.add(bone);const slot={character:{object:actor,animation:{paused:false}}},scene={characters:[slot],characterSelected:slot};const entries=new Map([[bone.uuid,{bone,offsets:new THREE.Vector3(),positionOffsets:new THREE.Vector3()}]]);const manualPoseByCharacter=new WeakMap([[actor,entries]]),poseOrigins=new WeakMap([[actor,captureModelLocal(actor)]]),poseFrozenBases=new WeakMap();const deps={THREE,scene,manualPoseByCharacter,poseOrigins,poseFrozenBases,writeLocal,captureModelLocal,clampPoseJoint:()=>false,isPerformanceBoneLeased:()=>false,syncDirectPoseOffsetsFromBone(){},directPoseTarget:undefined,document:{body:{classList:{contains:()=>false}}}};const api=Function(...Object.keys(deps),code+';return {freeze:freezePoseForEditing,frame:applyManualPoseOverrides,restore:restoreManualPoseOverrides}')(...Object.values(deps));return{actor,bone,slot,entry:entries.get(bone.uuid),api,poseFrozenBases}}
test('paused edit freezes actual cloth reference across native simulation, including zero-offset reset',()=>{const f=fixture(),initial=readLocal(f.bone);f.api.freeze(f.actor);for(let i=0;i<80;i++){f.api.restore();f.bone.rotation.z+=.01;f.api.frame();for(const key of ['p','q','s'])assert.ok(readLocal(f.bone)[key].every((n,i)=>Math.abs(n-initial[key][i])<1e-12))}assert.equal(f.slot.character.animation.paused,true)})
test('relative position and scale are applied once and removed before native animation',()=>{const f=fixture();f.api.freeze(f.actor);f.entry.unrestricted=true;f.entry.positionOffsets.x=.2;f.entry.scaleFactors=new THREE.Vector3(1.2,1,1);for(let i=0;i<120;i++){f.api.frame();assert.ok(Math.abs(f.bone.position.x-.2)<1e-9);assert.ok(Math.abs(f.bone.scale.x-1.2)<1e-9);f.api.restore();assert.equal(f.bone.position.x,0);assert.equal(f.bone.scale.x,1)}})
test('resuming animation releases the frozen reference instead of locking future playback',()=>{const f=fixture();f.api.freeze(f.actor);f.api.frame();f.api.restore();f.slot.character.animation.paused=false;f.bone.rotation.z=.8;f.api.frame();assert.equal(f.poseFrozenBases.has(f.actor),false);assert.ok(Math.abs(f.bone.rotation.z-.8)<1e-9)})
