import assert from 'node:assert/strict';import test,{after}from'node:test';import fs from'node:fs';import path from'node:path';import{pathToFileURL}from'node:url';import{build}from'esbuild';import{JSDOM}from'jsdom';import{Group,PerspectiveCamera,Vector3}from'three';import{ThirdPersonCamera}from'./src/viewer/ThirdPersonCamera.ts';
const temp=fs.mkdtempSync(path.resolve('.studio-followup-'));after(()=>fs.rmSync(temp,{recursive:true,force:true}));await build({entryPoints:['src/viewer/viewportPoseEditor.ts','src/viewer/runtimeSelectionPanels.ts','src/viewer/performanceEditor/studio.ts'],outdir:temp,bundle:true,platform:'node',format:'esm',outExtension:{'.js':'.mjs'},external:['three'],logLevel:'silent'});const{avoidDefaultChipOverlap,poseLeaderColour}=await import(pathToFileURL(path.join(temp,'viewportPoseEditor.mjs')));const{setupRuntimeSelectionPanels}=await import(pathToFileURL(path.join(temp,'runtimeSelectionPanels.mjs')));const{mountPerformanceStudio}=await import(pathToFileURL(path.join(temp,'performanceEditor/studio.mjs')));
function dom(t,html='<canvas></canvas>'){const d=new JSDOM(html,{url:'https://example.test/',pretendToBeVisual:true}),w=d.window,old=new Map();for(const[k,v]of Object.entries({window:w,document:w.document,Element:w.Element,Event:w.Event,CustomEvent:w.CustomEvent,HTMLElement:w.HTMLElement,MutationObserver:w.MutationObserver,AbortController:w.AbortController,localStorage:w.localStorage,innerWidth:1000,innerHeight:800,ResizeObserver:class{observe(){}disconnect(){}},fetch:async()=>({ok:true,json:async()=>({schema:'magius.runtime-selection-thumbnails.v1',characters:{},scenes:{a:'/a.png',b:'/b.png',pending:'/pending.png'},sceneResources:{}})})})){old.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,configurable:true,writable:true})}const captures=new Map();w.Element.prototype.setPointerCapture=function(id){captures.set(id,this)};w.Element.prototype.hasPointerCapture=function(id){return captures.get(id)===this};w.Element.prototype.releasePointerCapture=function(id){captures.delete(id)};t.after(()=>{w.close();for(const[k,v]of old){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k]}});return w}
for(const modifier of ['ctrlKey','metaKey','shiftKey'])test('released TPS '+modifier+' + left drag pans with unchanged optical rotation',t=>{const w=dom(t),canvas=document.querySelector('canvas');canvas.getBoundingClientRect=()=>({left:0,top:0,right:1000,bottom:800,width:1000,height:800});Object.defineProperty(canvas,'clientHeight',{value:800});const camera=new PerspectiveCamera(45,1.25,.01,100),actor=new Group();camera.position.set(0,1,4);camera.lookAt(0,1,0);const controls={target:new Vector3(0,1,0),enabled:true,rotateSpeed:1,panSpeed:1,zoomSpeed:1,disconnect(){},connect(){},update(){}};const c=new ThirdPersonCamera({scene:()=>({camera,controls,renderer:{domElement:canvas}}),actor:()=>actor,status(){},released(){}});c.install();c.start();const rotation=camera.quaternion.toArray(),target=controls.target.clone();canvas.dispatchEvent(new w.PointerEvent('pointerdown',{bubbles:true,cancelable:true,pointerId:1,pointerType:'mouse',button:0,clientX:400,clientY:300,[modifier]:true}));document.dispatchEvent(new w.PointerEvent('pointermove',{bubbles:true,pointerId:1,pointerType:'mouse',buttons:1,clientX:460,clientY:340,[modifier]:true}));c.update();assert.ok(controls.target.distanceTo(target)>.01);assert.ok(camera.quaternion.toArray().every((v,i)=>Math.abs(v-rotation[i])<1e-9));document.dispatchEvent(new w.PointerEvent('pointerup',{pointerId:1,bubbles:true,pointerType:'mouse'}));c.stop()});
test('default chips never overlap after height reduction; deliberate manual overlap is retained',()=>{const base=Array.from({length:9},(_,i)=>({key:String(i),x:210,y:60,width:90,height:28,manual:false})),view={left:4,right:400,top:4,bottom:250},r=avoidDefaultChipOverlap(base,view),rects=base.map(b=>({...b,...r.get(b.key)}));for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++){const a=rects[i],b=rects[j];assert.ok(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y)}const manual=avoidDefaultChipOverlap([{...base[0],manual:true},{...base[1],manual:true},base[2]],view);assert.deepEqual(manual.get('0'),manual.get('1'));assert.notDeepEqual(manual.get('2'),manual.get('0'))});
test('all visible leaders have different stable hues, selected brightness increases without glow',()=>{for(const count of [3,18,30]){const normal=Array.from({length:count},(_,i)=>poseLeaderColour(i,count));assert.equal(new Set(normal).size,count);for(let i=0;i<count;i++){const selected=poseLeaderColour(i,count,true),a=normal[i].match(/[\d.]+/g).map(Number),b=selected.match(/[\d.]+/g).map(Number);assert.equal(a[0],b[0]);assert.ok(b[2]-a[2]>=20)}}});
test('pending scenes can be selected and previewed after a load, but never loaded as real scenes',async t=>{dom(t,fs.readFileSync('index.html','utf8'));for(const id of ['stage-selector','character-selector']){const select=document.getElementById(id);select.replaceChildren();for(const[value,disabled]of[['a',false],['b',false],['pending',true]]){const o=document.createElement('option');o.value=value;o.textContent=value;o.disabled=disabled;o.dataset.official='true';select.append(o)}}let loads=0;const source=document.getElementById('stage-selector');source.addEventListener('change',()=>loads++);setupRuntimeSelectionPanels();await new Promise(r=>setTimeout(r,0));document.getElementById('stage-list-panel-toggle').click();const tile=value=>document.querySelector('#stage-list-grid [data-value="'+value+'"]');tile('a').click();document.getElementById('stage-list-use').click();assert.equal(loads,1);tile('pending').click();assert.equal(document.getElementById('stage-list-select').value,'pending');assert.match(document.getElementById('stage-list-detail').textContent,/pending/);assert.ok(tile('pending').classList.contains('is-selected'));assert.equal(document.getElementById('stage-list-use').disabled,true);document.getElementById('stage-list-use').click();assert.equal(loads,1);assert.match(document.getElementById('stage-list-preview').src,/pending.png/);source.disabled=true;await new Promise(r=>setTimeout(r,0));source.disabled=false;await new Promise(r=>setTimeout(r,0));assert.equal(document.getElementById('stage-list-select').value,'pending');tile('b').click();assert.equal(document.getElementById('stage-list-use').disabled,false);document.getElementById('stage-list-use').click();assert.equal(loads,2);assert.equal(source.value,'b');assert.equal(source.options[2].disabled,true,'preview fix must not remove the restoration eligibility gate')});

test('studio defaults to the asynchronously loaded current actor and preserves explicitly selected camera',t=>{
 dom(t,'<button id="toggle"></button>');const actor={actorKey:'actual-A',label:'A',instance:0,current:()=>true};let ready=false,selected,listener;
 const runtime={time:0,playing:false,lastError:null,timeline:{recordedLanes:[],tracks:[],audioTracks:[],duration:10,loop:false},subscribe(fn){listener=fn;return()=>{}},pause(){},exportProject(){return '{}'}};
 const recorder={runtime,host:{actors:()=>ready?[actor]:[]},lanes:[],recording:false,canUndo:false,canRedo:false,subscribe:()=>()=>{},prepareLive(){},stop(){}};
 const studio=mountPerformanceStudio({toggle:document.querySelector('#toggle'),panel:{},recorder,selected:()=>selected,pose(){},expression(){},tps(){},focus(){}});
 assert.equal(document.querySelector('#studio-target').value,'camera');ready=true;selected='actual-A';listener('actors');studio.setOpen(true);assert.equal(document.querySelector('#studio-target').value,'actual-A');
 const chooser=document.querySelector('#studio-target');chooser.value='camera';chooser.dispatchEvent(new Event('change',{bubbles:true}));listener('actors');assert.equal(chooser.value,'camera');studio.dispose();
});
