import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test, {after} from 'node:test'
import {pathToFileURL} from 'node:url'
import ts from 'typescript'
import * as T from 'three'
const temp=fs.mkdtempSync(path.resolve('.viewport-tests-'))
after(()=>fs.rmSync(temp,{recursive:true,force:true}))
const modules=['poseJointLimits','editorGround','directPoseTools','directPoseTarget','poseContactGuard','viewportPoseEditor','objectMovementSelection']
for(const name of modules){let source=fs.readFileSync(`src/viewer/${name}.ts`,'utf8');for(const dep of modules)source=source.replaceAll(`'./${dep}'`,`'./${dep}.mjs'`);fs.writeFileSync(path.join(temp,name+'.mjs'),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText)}
const {registerPoseJointLimits,clampPoseJoint,poseJointLimitSnapshot,constrainBendPole}=await import(pathToFileURL(path.join(temp,'poseJointLimits.mjs')))
const {EditorGroundGuard,liftWorld}=await import(pathToFileURL(path.join(temp,'editorGround.mjs')))
const {DirectPoseTarget,directPoseTranslationJoints}=await import(pathToFileURL(path.join(temp,'directPoseTarget.mjs')))
const {findDirectPoseParts}=await import(pathToFileURL(path.join(temp,'directPoseTools.mjs')))
const {clampEditorPosition}=await import(pathToFileURL(path.join(temp,'viewportPoseEditor.mjs')))
const {ObjectMovementSelection}=await import(pathToFileURL(path.join(temp,'objectMovementSelection.mjs')))
function rig(leg=false){const actor=new T.Group(),root=new T.Bone(),upper=new T.Bone(),lower=new T.Bone(),tip=new T.Bone(),toe=new T.Bone();root.name='Root';upper.name=leg?'UpLeg_R':'Arm_R';lower.name=leg?'Leg_R':'Forearm_R';tip.name=leg?'Foot_R':'Hand_R';toe.name=leg?'Toe_R':'Middlefinger_R';actor.add(root);root.add(upper);upper.add(lower);lower.add(tip);tip.add(toe);upper.position.set(0,1.5,0);lower.position.set(leg?0:.45,leg?-.45:0,0);tip.position.copy(lower.position);toe.position.set(leg?0:.1,0,leg?.1:0);actor.updateMatrixWorld(true);registerPoseJointLimits(actor);return{actor,root,upper,lower,tip,toe}}
for(const leg of [false,true])test((leg?'knee':'elbow')+' has a fixed one-sided bind-space hinge',()=>{const f=rig(leg),snap=poseJointLimitSnapshot(f.lower);assert.equal(snap.hinge,true);for(const axis of [new T.Vector3(1,0,0),new T.Vector3(0,1,0),new T.Vector3(0,0,1)])for(const value of [-3,-1,1,3]){f.lower.quaternion.setFromAxisAngle(axis,value);clampPoseJoint(f.lower);const s=poseJointLimitSnapshot(f.lower);assert.ok(s.flexion>=-1e-8&&s.flexion<=s.maximumFlexion+1e-8);assert.ok(f.lower.quaternion.toArray().every(Number.isFinite))}})
for(const name of ['Hand_R','Foot_R','Head','Chest'])test(name+' repeated local edits cannot accumulate unlimited rotation',()=>{const f=rig();f.tip.name=name;const actor=new T.Group(),b=new T.Bone(),child=new T.Bone();b.name=name;child.name='end';child.position.x=.2;actor.add(b);b.add(child);registerPoseJointLimits(actor);const position=b.position.clone(),scale=b.scale.clone();for(let i=0;i<500;i++){b.quaternion.multiply(new T.Quaternion().setFromEuler(new T.Euler(.13,-.11,.09)));clampPoseJoint(b);assert.ok(b.quaternion.angleTo(new T.Quaternion())<2.7)}assert.deepEqual(b.position.toArray(),position.toArray());assert.deepEqual(b.scale.toArray(),scale.toArray())})
test('reselection never redefines bind-pose constraints',()=>{const f=rig();for(let i=0;i<100;i++){new DirectPoseTarget(f.actor,f.tip);f.tip.rotateZ(.3);clampPoseJoint(f.tip)}assert.ok(f.tip.quaternion.angleTo(new T.Quaternion())<1.6)})
test('limits alone do not alter a native animation without an explicit editor write',()=>{const f=rig();f.lower.rotation.set(.8,.7,-.6);const q=f.lower.quaternion.clone();registerPoseJointLimits(f.actor);assert.deepEqual(f.lower.quaternion.toArray(),q.toArray())})
test('unrecognized auxiliary bones are not assigned invented human constraints',()=>{const f=rig();const b=new T.Bone();b.name='HairRibbon_01_Sp';f.actor.add(b);registerPoseJointLimits(f.actor);b.rotation.x=2.9;const q=b.quaternion.clone();assert.equal(clampPoseJoint(b),false);assert.deepEqual(q.toArray(),b.quaternion.toArray())})
test('elbow and real Leg_R buttons select hinge rotation instead of moving a hip ancestor',()=>{const f=rig(true),parts=findDirectPoseParts(f.actor);assert.equal(parts.find(p=>p.id==='right-knee')?.mode,'rotate');assert.equal(directPoseTranslationJoints(f.actor,f.lower).length,0);assert.deepEqual(directPoseTranslationJoints(f.actor,f.tip),[f.upper,f.lower])})
test('limited pole does not flip into the opposite bend hemisphere',()=>{const p=new T.Vector3(0,0,-1),axis=new T.Vector3(1,0,0);constrainBendPole(p,axis,new T.Vector3(0,0,1));assert.ok(p.z>0);assert.ok(Math.abs(p.dot(axis))<1e-9)})
for(const leg of [false,true])test((leg?'leg':'arm')+' extreme IK samples remain finite and do not resize the skeleton',()=>{const f=rig(leg),bones=[f.root,f.upper,f.lower,f.tip],initial=bones.map(b=>({p:b.position.toArray(),s:b.scale.toArray()})),target=new DirectPoseTarget(f.actor,f.tip);assert.ok(target.begin('translate'));for(const p of [[100,-100,100],[0,1.5,0],[-10,10,-10],[.1,.7,.2]]){target.handle.position.fromArray(p);target.queue();target.flush();for(let i=0;i<bones.length;i++){assert.deepEqual(bones[i].position.toArray(),initial[i].p);assert.deepEqual(bones[i].scale.toArray(),initial[i].s);assert.ok(bones[i].quaternion.toArray().every(Number.isFinite))}const s=poseJointLimitSnapshot(f.lower);assert.ok(s.flexion>=-1e-8&&s.flexion<=s.maximumFlexion+1e-8)}})
function floorFixture(y=0){const root=new T.Group(),active=new T.Group(),mesh=new T.Mesh(new T.PlaneGeometry(20,20),new T.MeshBasicMaterial());mesh.rotation.x=-Math.PI/2;mesh.position.y=y;mesh.name='ground';active.add(mesh);root.add(active);root.userData.stageDefinition={id:'floor',spawnPoints:[{role:'ally',position:[0,y,0]}]};root.updateMatrixWorld(true);return{root,active,mesh,guard:new EditorGroundGuard(()=>root)}}
test('floor guard uses actual scene triangles without changing source materials',()=>{const f=floorFixture(2),material=f.mesh.material;assert.ok(Math.abs(f.guard.sample(1,1,2).height-2)<1e-9);assert.equal(f.guard.sample(1,1,2).source,'scene');assert.equal(f.mesh.material,material);f.guard.dispose();assert.equal(f.mesh.geometry.getAttribute('position').count,4)})
test('empty scene uses the explicit reference floor',()=>{const g=new EditorGroundGuard(()=>undefined);assert.deepEqual(g.sample(0,0,-100),{height:0,source:'reference-plane'});g.dispose()})
test('vertical walls and invisible surfaces do not become floor',()=>{const f=floorFixture();f.mesh.rotation.x=0;f.root.updateMatrixWorld(true);assert.equal(f.guard.sample(0,1).source,'reference-plane');f.mesh.visible=false;assert.equal(f.guard.sample(0,0).source,'reference-plane');f.guard.dispose()})
test('root and lower prop geometry cannot be moved below ground',()=>{const f=floorFixture(),parent=new T.Group(),object=new T.Mesh(new T.BoxGeometry(1,2,1),new T.MeshBasicMaterial());parent.add(object);object.position.y=2;f.guard.capture(object);object.position.y=-50;assert.equal(f.guard.constrainObject(object),true);assert.ok(new T.Box3().setFromObject(object).min.y>=-1e-6);const queries=f.guard.queries;for(let i=0;i<100;i++)f.guard.constrainObject(object);assert.equal(f.guard.queries,queries,'idle frames do not repeat ground raycasts');f.guard.dispose()})
test('world upward correction works under rotated and scaled parents',()=>{const parent=new T.Group(),object=new T.Object3D();parent.rotation.z=.3;parent.scale.set(.7,1.5,.9);parent.add(object);parent.updateMatrixWorld(true);const before=object.getWorldPosition(new T.Vector3());liftWorld(object,2);const after=object.getWorldPosition(new T.Vector3());assert.ok(Math.abs(after.y-before.y-2)<1e-6);assert.ok(Math.abs(after.x-before.x)<1e-6)})
test('movement arrow pad invokes floor constraint for every target type',()=>{const g=new EditorGroundGuard(()=>undefined),scene=new T.Scene(),o=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial());scene.add(o);const move=new ObjectMovementSelection(()=>false,x=>g.constrainObject(x));move.select({object:o,label:'prop'});move.move(new T.PerspectiveCamera(),0,-100);assert.ok(new T.Box3().setFromObject(o).min.y>=0);g.dispose()})
for(const enabled of [false,true])test('camera floor enforcement with Orbit enabled='+enabled,()=>{const f=floorFixture(),camera=new T.PerspectiveCamera(40,1,.05,100);camera.position.set(0,-30,4);const controls={enabled,target:new T.Vector3(0,-20,0),maxPolarAngle:Math.PI};assert.equal(f.guard.constrainCamera(camera,controls),true);assert.ok(camera.position.y>=.08);if(enabled){assert.ok(controls.target.y>=.02);assert.ok(controls.maxPolarAngle<Math.PI)}f.guard.dispose()})
test('camera above ground is not needlessly repositioned',()=>{const f=floorFixture(),camera=new T.PerspectiveCamera(40,1,.05,100);camera.position.set(0,3,4);const before=camera.position.toArray(),controls={enabled:true,target:new T.Vector3(0,1,0),maxPolarAngle:Math.PI};f.guard.constrainCamera(camera,controls);assert.deepEqual(camera.position.toArray(),before);const q=f.guard.queries;f.guard.constrainCamera(camera,controls);assert.equal(q,f.guard.queries);f.guard.dispose()})
for(const size of [[360,780],[430,932],[1366,900]])test('floating card stays inside viewport '+size.join('x'),()=>{const p=clampEditorPosition(-100,5000,Math.min(300,size[0]-16),240,...size);assert.ok(p.x>=8&&p.y>=8);assert.ok(p.x+Math.min(300,size[0]-16)<=size[0]-8);assert.ok(p.y+240<=size[1]-8)})
const index=fs.readFileSync('src/viewer/index.ts','utf8'),css=fs.readFileSync('src/viewer/style/viewport-editor.css','utf8'),html=fs.readFileSync('index.html','utf8')
test('camera ground contact and orbit angle clamp share one stable numerical margin',()=>{const f=floorFixture(-.015),camera=new T.PerspectiveCamera(40,1,.1,100),controls={enabled:true,target:new T.Vector3(-.05,.84,0),maxPolarAngle:Math.PI};camera.position.set(-2.7,-.5,1.5);f.guard.constrainCamera(camera,controls);const initial=camera.position.clone();for(let i=0;i<250;i++){const delta=camera.position.clone().sub(controls.target),sphere=new T.Spherical().setFromVector3(delta);sphere.phi=Math.min(sphere.phi,controls.maxPolarAngle);camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(sphere));f.guard.constrainCamera(camera,controls)}assert.ok(camera.position.distanceTo(initial)<1e-6,'Floor correction accumulated camera drift');assert.ok(camera.position.y>=.135-1e-7);f.guard.dispose()})
test('an unnamed sky dome is not a floor underneath the playable ground',()=>{const f=floorFixture(),sky=new T.Mesh(new T.SphereGeometry(35,16,12),new T.MeshBasicMaterial({side:T.BackSide}));sky.renderOrder=-100;f.active.add(sky);f.root.updateMatrixWorld(true);const sample=f.guard.sample(30,0,0);assert.equal(sample.source,'reference-plane');assert.equal(sample.height,0);f.guard.dispose()})
test('native parked weapons are not character ground contacts but standalone weapons remain constrained',()=>{const g=new EditorGroundGuard(()=>undefined),scene=new T.Scene(),actor=new T.Group(),body=new T.Mesh(new T.BoxGeometry(1,2,1),new T.MeshBasicMaterial()),weapon=new T.Mesh(new T.BoxGeometry(.01,.01,.01),new T.MeshBasicMaterial());body.name='Body_Mesh';body.position.y=1;weapon.name='weapon_a_mesh';weapon.position.y=-10;actor.add(body,weapon);scene.add(actor);g.capture(actor);g.constrainObject(actor);assert.ok(Math.abs(actor.position.y)<1e-6);scene.attach(weapon);g.capture(weapon);g.constrainObject(weapon);assert.ok(new T.Box3().setFromObject(weapon).min.y>=0);g.dispose()})
test('invisible legacy helpers cannot lift the actor ten metres above ground',()=>{const g=new EditorGroundGuard(()=>undefined),scene=new T.Scene(),actor=new T.Group(),body=new T.Mesh(new T.BoxGeometry(1,2,1),new T.MeshBasicMaterial()),hidden=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial());body.position.y=1;hidden.position.y=-10;hidden.visible=false;actor.add(body,hidden);scene.add(actor);g.capture(actor);g.constrainObject(actor);assert.ok(Math.abs(actor.position.y)<1e-6);g.dispose()})
test('joint selection clears mesh visibility selection and does not auto-scroll',()=>{const select=index.slice(index.indexOf('function selectDirectPoseBone'),index.indexOf('function clearDirectPoseSelection'));assert.match(select,/selectModelPart\(undefined\)/);assert.doesNotMatch(select,/selectModelPart\(getModelPart|updateDirectPoseUi\(true\)/);const ui=index.slice(index.indexOf('function updateDirectPoseUi'),index.indexOf('function updateDirectPoseTarget'));assert.doesNotMatch(ui,/scrollIntoView/);assert.match(index,/official-outline:/)})
test('main viewport mode has explicit translate/rotate/close and stays independent of panel visibility',()=>{const s=fs.readFileSync('src/viewer/viewportPoseEditor.ts','utf8');for(const id of ['move','rotate','pose','object','parameters','fine'])assert.ok(s.includes("'"+id+"'"));assert.match(s,/viewport-editor-close/);assert.doesNotMatch(s,/actionPanel\.classList/);assert.match(s,/data\.viewportJoint|dataset\.viewportJoint/);assert.match(css,/pointer-events:none/);assert.match(css,/grid-column:1\/-1/)})
test('advanced mesh controls are deliberately separate from the compact primary pose panel',()=>{assert.match(html,/id="mesh-visibility-details"/);assert.match(html,/id="bone-parameter-details"/);assert.doesNotMatch(html,/<details[^>]*id="mesh-visibility-details"[^>]*\bopen\b/);assert.match(css,/overflow-anchor:none/);assert.match(css,/overflow-x:hidden/)})
