import assert from 'node:assert/strict'
import test from 'node:test'
import fs from 'node:fs'
import ts from 'typescript'
import {JSDOM} from 'jsdom'
import {onPermanentPageExit,installContextRecovery} from './src/viewer/pageLifecycle.ts'
import {readWorkspaceSession,writeWorkspaceSession} from './src/viewer/sessionWorkspace.ts'
import {TpsViewGesture} from './src/viewer/TpsViewTouch.ts'
const orientationSource=fs.readFileSync(new URL('./src/viewer/compactWorkspace.ts',import.meta.url),'utf8')
const parsed=ts.createSourceFile('c.ts',orientationSource,ts.ScriptTarget.Latest,true)
const fn=parsed.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='setupOrientationToggle')
const compiled=ts.transpileModule(fn.getText(parsed).replace('export function','function'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText
function dom(t){const d=new JSDOM('<button id="orientation"></button><canvas></canvas>',{url:'https://fixture.test',pretendToBeVisual:true}),before=new Map(['window','document','screen'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));for(const k of before.keys())Object.defineProperty(globalThis,k,{configurable:true,writable:true,value:d.window[k]});t.after(()=>{d.window.close();for(const[k,v]of before){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k]}});return d.window}
test('parked BFCache document is not disposed, permanent navigation cleans up exactly once',t=>{const w=dom(t);let disposed=0;onPermanentPageExit(()=>disposed++);w.dispatchEvent(new w.PageTransitionEvent('pagehide',{persisted:true}));assert.equal(disposed,0);w.dispatchEvent(new w.PageTransitionEvent('pageshow',{persisted:true}));w.dispatchEvent(new w.PageTransitionEvent('pagehide',{persisted:false}));assert.equal(disposed,1);w.dispatchEvent(new w.PageTransitionEvent('pagehide',{persisted:false}));assert.equal(disposed,1)})
test('graphics loss is prevented and restore is observed without navigating/recreating a document',t=>{const w=dom(t),canvas=w.document.querySelector('canvas');installContextRecovery(canvas);const loss=new w.Event('webglcontextlost',{cancelable:true});canvas.dispatchEvent(loss);assert.equal(loss.defaultPrevented,true);assert.equal(w.document.documentElement.dataset.webglState,'lost');canvas.dispatchEvent(new w.Event('webglcontextrestored'));assert.equal(w.document.documentElement.dataset.webglState,'restored');assert.equal(w.magiusPageRecovery().losses,1);assert.equal(w.magiusPageRecovery().restores,1)})
test('orientation button enters landscape and second activation returns portrait and exits fullscreen',async t=>{const w=dom(t),events=[];let full=null;Object.defineProperty(w.document,'fullscreenElement',{get:()=>full});w.document.documentElement.requestFullscreen=async()=>{full=w.document.documentElement;events.push('fullscreen')};w.document.exitFullscreen=async()=>{full=null;events.push('exit')};Object.defineProperty(w.screen,'orientation',{value:{lock:async type=>events.push(type),unlock:()=>events.push('unlock')},configurable:true});const setup=Function(compiled+';return setupOrientationToggle')();const button=w.document.querySelector('button');setup(button);await button.onclick();assert.equal(button.dataset.orientation,'landscape');await button.onclick();assert.equal(button.dataset.orientation,'portrait');assert.deepEqual(events,['fullscreen','landscape','portrait','exit','unlock'])})
test('orientation unavailable does not strand a fullscreen document or leave button disabled',async t=>{const w=dom(t);let full=null;Object.defineProperty(w.document,'fullscreenElement',{get:()=>full});w.document.documentElement.requestFullscreen=async()=>{full=w.document.documentElement};w.document.exitFullscreen=async()=>{full=null};Object.defineProperty(w.screen,'orientation',{value:{lock:async()=>{throw new w.DOMException('unsupported','NotSupportedError')},unlock(){}},configurable:true});const b=w.document.querySelector('button');Function(compiled+';return setupOrientationToggle')()(b);await b.onclick();assert.equal(b.disabled,false);assert.equal(b.dataset.orientation,'landscape');await b.onclick();assert.equal(full,null);assert.equal(b.dataset.orientation,'portrait')})
test('two-finger centroid movement pans while spread zooms, without rotating',()=>{const r=[],p=[],z=[];const g=new TpsViewGesture({rotate:(...x)=>r.push(x),pan:(...x)=>p.push(x),pinch:x=>z.push(x)});g.begin({id:1,x:0,y:0});g.begin({id:2,x:100,y:0});g.move([{id:1,x:20,y:30},{id:2,x:120,y:30}]);assert.deepEqual(p.at(-1),[20,30]);assert.equal(z.at(-1),1);assert.equal(r.length,0);g.move([{id:1,x:0,y:30},{id:2,x:140,y:30}]);assert.deepEqual(p.at(-1),[0,0]);assert.ok(z.at(-1)<1);g.end([1]);g.move([{id:2,x:150,y:34}]);assert.deepEqual(r.at(-1),[10,4])})
const fixture=()=>({schema:'magius.workspace-session.v1',savedAt:new Date().toISOString(),actors:[{id:'100107',placement:{p:[1,0,0],q:[0,0,0,1],s:[1,1,1]}}],selected:0,camera:{p:[0,1,3],q:[0,0,0,1],target:[0,1,0]},allowStretch:false,stage:'flat'})
test('session checkpoints roundtrip and corrupt/no-finite data never drives a model load',()=>{let text=null;const storage={getItem:()=>text,setItem:(_,x)=>text=x},v=fixture();writeWorkspaceSession(storage,v);assert.deepEqual(readWorkspaceSession(storage),v);for(const edit of [v=>v.actors[0].id='../secret',v=>v.selected=10,v=>v.actors[0].placement.s=[0,1,1],v=>v.camera.p=['NaN',1,2],v=>v.actors=[]]){const invalid=fixture();edit(invalid);text=JSON.stringify(invalid);assert.throws(()=>readWorkspaceSession(storage))}})
