/** Japanese presentation strings for the Viewer UI. Canonical keys remain English. */
export const jaJpUiText: Readonly<Record<string, string>> = {
    "UI language": "UI言語",
    "Magius3Dviewer is loading the official-style shader and character model...": "Magius3Dviewer は公式スタイルのシェーダーとキャラクターモデルを読み込んでいます…",
    "Take a photo": "写真を撮る",
    "Model": "キャラクターモデル",
    "Choose model": "キャラクターモデルを選択",
    "Remove selected model": "選択中のモデルを削除",
    "<No target selected>": "<対象未選択>",
    "Add model": "モデルを追加",
    "Search:": "検索：",
    "ID / Name": "ID／名前",
    "Search characters by name or ID": "キャラクターを名前またはIDで検索",
    "Characters": "キャラクター",
    "Show character list": "キャラクター一覧を表示",
    "Hide character list": "キャラクター一覧を閉じる",
    "Search characters": "キャラクターを検索",
    "Character list": "キャラクター一覧",
    "Selected character": "選択中のキャラクター",
    "No character selected": "キャラクターが選択されていません",
    "Available characters": "利用可能なキャラクター",
    "Matching characters": "一致するキャラクター",
    "No matching characters": "一致するキャラクターはありません",
    "Switch character": "キャラクターを切り替える",
    "Character selected in viewer": "ビューアーでキャラクターを選択しました",
    "Magical girls": "魔法少女",
    "Show magical girl list": "魔法少女一覧を表示",
    "Hide magical girl list": "魔法少女一覧を閉じる",
    "Search magical girls": "魔法少女を検索",
    "Magical girl list": "魔法少女一覧",
    "Selected magical girl": "選択中の魔法少女",
    "No magical girl selected": "魔法少女が選択されていません",
    "Available magical girls": "利用可能な魔法少女",
    "Matching magical girls": "一致する魔法少女",
    "No matching magical girls": "一致する魔法少女はありません",
    "Switch magical girl": "魔法少女を切り替える",
    "Magical girl selected in viewer": "ビューアーで魔法少女を選択しました",
    "Show scene list": "シーン一覧を表示",
    "Hide scene list": "シーン一覧を閉じる",
    "Search scenes": "シーンを検索",
    "Scene list": "シーン一覧",
    "Selected scene": "選択中のシーン",
    "No scene selected": "シーンが選択されていません",
    "Available scenes": "利用可能なシーン",
    "Matching scenes": "一致するシーン",
    "No matching scenes": "一致するシーンはありません",
    "Load selected scene": "選択したシーンを読み込む",
    "Scene selected in viewer": "ビューアーでシーンを選択しました",
    "Enemies": "敵",
    "Choose enemy": "敵を選択",
    "Add selected enemy": "選択した敵を追加",
    "Show enemies": "敵一覧を表示",
    "Hide enemies": "敵一覧を閉じる",
    "Search enemies": "敵を検索",
    "Type a name or ID": "名前またはIDを入力",
    "Enemy list": "敵一覧",
    "Enemy animation loop": "敵の動作をループ",
    "Enemy animation speed": "敵の動作速度",
    "Play enemy animation": "敵の動作を再生",
    "Enemy animation": "敵の動作",
    "Pause enemy animation": "敵の動作を一時停止",
    "Resume enemy animation": "敵の動作を再開",
    "Enemy animation paused": "敵の動作を一時停止中",
    "Enemy animation playing": "敵の動作を再生中",
    "Selected enemy": "選択中の敵",
    "No enemy selected": "敵が選択されていません",
    "Quantity": "数量",
    "Add enemy": "敵を追加",
    "Active enemies": "配置中の敵",
    "No enemies added": "敵はまだ追加されていません",
    "Remove": "削除",
    "Clear all": "すべて削除",
    "Loading enemy list...": "敵一覧を読み込んでいます…",
    "Available enemies": "利用可能な敵",
    "Matching enemies": "一致する敵",
    "No matching enemies": "一致する敵はありません",
    "Adding enemy...": "敵を追加しています…",
    "Adding enemies...": "敵を一括追加しています…",
    "Enemy added": "敵を追加しました",
    "Enemies added": "敵を追加しました",
    "Enemy removed": "敵を削除しました",
    "All enemies removed": "すべての敵を削除しました",
    "Enemy list could not be loaded": "敵一覧を読み込めませんでした",
    "Enemy data is invalid": "敵データが正しくありません",
    "Enemy was not found": "敵が見つかりません",
    "Enemy model is not ready": "敵モデルの準備ができていません",
    "Enemy model could not be loaded": "敵モデルを読み込めませんでした",
    "Enemy model could not be read": "敵モデルを解析できませんでした",
    "Unexpected enemy error": "敵の処理中に予期しないエラーが発生しました",
    "Combat effects": "戦闘エフェクト",
    "Show combat effects": "戦闘エフェクトを表示",
    "Hide combat effects": "戦闘エフェクトを閉じる",
    "Enable combat effects": "戦闘エフェクトを有効にする",
    "Effect source": "エフェクトの種類",
    "All combat effects": "すべての戦闘エフェクト",
    "Enemy combat effects": "敵の戦闘エフェクト",
    "Magical girl combat effects": "魔法少女の戦闘エフェクト",
    "Search combat effects": "戦闘エフェクトを検索",
    "Type a stable key or direction key": "Stable KeyまたはDirection Keyを入力",
    "Combat effect list": "戦闘エフェクト一覧",
    "Loading combat effects...": "戦闘エフェクトを読み込んでいます…",
    "Combat effects could not be loaded": "戦闘エフェクトを読み込めませんでした",
    "Available combat effects": "利用可能な戦闘エフェクト",
    "Matching combat effects": "一致する戦闘エフェクト",
    "No matching combat effects": "一致する戦闘エフェクトはありません",
    "Selected combat effect": "選択中の戦闘エフェクト",
    "No combat effect selected": "戦闘エフェクトが選択されていません",
    "Playable": "再生可能",
    "Direction key": "Direction Key",
    "Unavailable reason": "利用できない理由",
    "Play selected effect": "選択したエフェクトを再生",
    "Stop all effects": "すべてのエフェクトを停止",
    "Installed": "接続済み",
    "Active effects": "再生中のエフェクト",
    "Suppressed cues": "抑制されたキュー",
    "Combat effects enabled": "戦闘エフェクトを有効にしました",
    "Combat effects disabled; active effects cleared": "戦闘エフェクトを無効にし、再生中のエフェクトを消去しました",
    "All combat effects stopped": "すべての戦闘エフェクトを停止しました",
    "Loading selected combat effect...": "選択した戦闘エフェクトを読み込んでいます…",
    "Combat effect started": "戦闘エフェクトを再生しました",
    "Combat effect cue suppressed": "戦闘エフェクトのキューを抑制しました",
    "Combat effect could not be played": "戦闘エフェクトを再生できませんでした",
    "Voice / Subtitles": "ボイス／字幕",
    "Home voice": "ホームボイス",
    "Show voice and subtitles": "ボイスと字幕を表示",
    "Hide voice and subtitles": "ボイスと字幕を閉じる",
    "Auto sequence": "順次再生",
    "Subtitles": "字幕",
    "Subtitle language": "字幕言語",
    "Show subtitles": "字幕を表示",
    "Follow original motion": "元のモーションに追従",
    "Follow original expression": "元の表情に追従",
    "Subtitle source": "字幕ソース",
    "Official subtitle language": "公式字幕言語",
    "Fallback": "代替",
    "Voice list": "ボイス一覧",
    "Loading voice catalog...": "ボイス一覧を読み込んでいます…",
    "Voice catalog ready": "ボイス一覧の準備ができました",
    "Voice catalog could not be loaded": "ボイス一覧を読み込めませんでした",
    "Select a magical girl to view voices": "魔法少女を選択するとボイスを表示できます",
    "Voices": "件のボイス",
    "Selected voice": "選択中のボイス",
    "No voice selected": "ボイスが選択されていません",
    "Voice playback controls": "ボイス再生操作",
    "Play sequence": "順次再生",
    "Multitrack audio": "マルチトラック音声",
    "Character tracks": "キャラクター音声トラック",
    "Background tracks": "背景音声トラック",
    "Background track": "背景音声トラック",
    "Upload audio": "音声をアップロード",
    "Add background track": "背景音声トラックを追加",
    "No loaded characters": "読み込み済みキャラクターがありません",
    "No background tracks": "背景音声トラックはありません",
    "No audio loaded": "音声が選択されていません",
    "Multitrack runtime is not connected": "マルチトラック実行環境が接続されていません",
    "Audio workspace operation failed": "音声トラック操作に失敗しました",
    "Clear track": "トラックをクリア",
    "Delete track": "トラックを削除",
    "Volume": "音量",
    "Loop": "ループ",
    "Background tracks do not drive lip sync": "背景音声トラックはリップシンクを駆動しません",
    "Previous": "前へ",
    "Next": "次へ",
    "Resume": "再開",
    "Voice timeline": "ボイス再生位置",
    "Order": "順番",
    "Cue name": "キュー名",
    "Playback": "再生状態",
    "Lip sync": "リップシンク",
    "Mouth carrier": "口パク制御対象",
    "idle": "待機中",
    "empty": "空",
    "loading": "読み込み中",
    "ready": "準備完了",
    "playing": "再生中",
    "paused": "一時停止中",
    "ended": "再生終了",
    "error": "エラー",
    "disposed": "解放済み",
    "multiwave": "マルチウェーブ",
    "official-binary": "公式二値",
    "Loading selected voice...": "選択したボイスを読み込んでいます…",
    "Voice playback started": "ボイスを再生しました",
    "Voice operation was not started": "ボイス操作は開始されませんでした",
    "Voice operation failed": "ボイス操作に失敗しました",
    "Loading voice sequence...": "ボイスキューを読み込んでいます…",
    "Voice sequence started": "ボイスの順次再生を開始しました",
    "Loading previous voice...": "前のボイスを読み込んでいます…",
    "Previous voice started": "前のボイスを再生しました",
    "Loading next voice...": "次のボイスを読み込んでいます…",
    "Next voice started": "次のボイスを再生しました",
    "Voice playback paused": "ボイスを一時停止しました",
    "Resuming voice...": "ボイスを再開しています…",
    "Voice playback resumed": "ボイスを再開しました",
    "Voice playback stopped": "ボイスを停止しました",
    "Resources": "リソース",
    "Show official resources": "公式リソースを表示",
    "Hide official resources": "公式リソースを閉じる",
    "Official resources": "公式リソース",
    "Resource type": "リソース種別",
    "Scenes": "シーン",
    "Enemy models": "敵モデル",
    "VFX": "VFX",
    "VFX domain": "VFX分類",
    "All VFX": "すべてのVFX",
    "Enemy VFX": "敵VFX",
    "Character VFX": "キャラクターVFX",
    "Search official resources": "公式リソースを検索",
    "Name, ID, or stable key": "名前、ID、またはStable Key",
    "Official resource list": "公式リソース一覧",
    "Loading official resources...": "公式リソースを読み込んでいます…",
    "Official resources could not be loaded": "公式リソースを読み込めませんでした",
    "Available official resources": "利用可能な公式リソース",
    "Matching official resources": "一致する公式リソース",
    "No matching official resources": "一致する公式リソースはありません",
    "Selected resource": "選択中のリソース",
    "No official resource selected": "公式リソースが選択されていません",
    "Use selected stage": "選択したステージをビューアーで使用",
    "Open in enemy panel": "敵パネルで選択",
    "No direct viewer action": "ビューアーで直接操作できません",
    "Open release preview": "リリースプレビューを開く",
    "Resource selected in viewer": "ビューアーでリソースを選択しました",
    "Runtime ready": "ランタイム利用可能",
    "Unavailable": "利用不可",
    "Stable key": "Stable Key",
    "Display name": "表示名",
    "English": "英語",
    "Japanese": "日本語",
    "Traditional Chinese": "繁体字中国語",
    "Family": "リソース系統",
    "Model key": "Model Key",
    "Record IDs": "レコードID",
    "Domain": "分類",
    "Owner": "提供元",
    "Direction": "方向",
    "Status": "状態",
    "Reason": "理由",
    "Scene is not present in the viewer selector": "ビューアーのシーン選択欄にこのシーンはありません",
    "Enemy is not present in the enemy selector": "敵選択欄にこの敵はありません",
    "This resource is not runtime-ready": "このリソースのランタイムは準備中です",
    "Animation": "アニメーション",
    "Choose animation": "アニメーションを選択",
    "Choose expression": "表情を選択",
    "Default face": "デフォルト表情",
    "Manual face controls": "表情の手動調整",
    "Auto blink": "自動まばたき",
    "Enable automatic blink for the selected expression": "選択した表情で自動まばたきを有効にする",
    "Manual blink": "手動まばたき",
    "Set eyelid closure using this character's official blink bindings": "このキャラクターの公式まばたきバインドでまぶたの閉じ具合を調整",
    "Expression strength": "表情の強さ",
    "Blend the selected official expression with this character's default face": "このキャラクターのデフォルト表情と選択した公式表情のブレンド量を調整",
    "Transition": "切り替え時間",
    "Set the transition duration used by the next expression selection": "次に表情を選択するときの切り替え時間を設定",
    "Mouth corner": "口角",
    "Adjust this character's available mouth-corner bindings": "このキャラクターで利用可能な口角バインドを調整",
    "Play animation": "アニメーションを再生",
    "Pause animation": "アニメーションを一時停止",
    "Loading official character actions...": "公式キャラクターアクションを読み込んでいます…",
    "Loading official character action...": "公式キャラクターアクションを読み込んでいます…",
    "Official character actions could not be loaded": "公式キャラクターアクションを読み込めませんでした",
    "No official character actions for this character": "このキャラクターの公式探索アクションはありません",
    "No playable official character actions": "再生可能な公式探索アクションはありません",
    "Playing official character action": "公式キャラクターアクションを再生中",
    "Paused official character action": "公式キャラクターアクションを一時停止中",
    "Official character action interrupted": "公式キャラクターアクションが中断されました",
    "Official character action unavailable": "公式キャラクターアクションは利用できません",
    "Choose 3D stage": "3Dステージを選択",
    "Collapse controls": "ツールバーを折りたたむ",
    "Expand controls": "ツールバーを展開",
    "Rendering controls": "レンダリング設定",
    "Show rendering controls": "レンダリング設定を表示",
    "Hide rendering controls": "レンダリング設定を閉じる",
    "Shadow quality": "影の品質",
    "Official quality": "公式品質",
    "Balanced": "バランス",
    "Performance first": "パフォーマンス優先",
    "Action panel": "アクションパネル",
    "Show action parameters": "アクションパラメーターを表示",
    "Hide action parameters": "アクションパラメーターを閉じる",
    "Action parameters": "アクションパラメーター",
    "Expression panel": "表情パネル",
    "Show expression parameters": "表情パラメーターを表示",
    "Hide expression parameters": "表情パラメーターを閉じる",
    "Expression parameters": "表情パラメーター",
    "Timeline": "タイムライン",
    "Animation speed": "アニメーション速度",
    "Bone search": "ボーン検索",
    "Search bones": "ボーンを検索",
    "Morph search": "モーフ検索",
    "Search morphs": "モーフを検索",
    "Bone": "ボーン",
    "Unnamed bone": "名前のないボーン",
    "No bone channels": "ボーンチャンネルはありません",
    "No morph channels": "モーフチャンネルはありません",
    "Select a character to edit action parameters": "キャラクターを選択するとアクションパラメーターを編集できます",
    "Select a character to edit expression parameters": "キャラクターを選択すると表情パラメーターを編集できます",
    "Reset action parameters": "アクションパラメーターをリセット",
    "Reset expression parameters": "表情パラメーターをリセット",
    "Direct drag pose": "直接ドラッグ編集",
    "Exit direct drag pose": "直接ドラッグ編集を終了",
    "Transform mode": "変形モード",
    "Move XYZ": "XYZ移動",
    "Rotate XYZ": "XYZ回転",
    "Click a body part, then drag the XYZ arrows": "身体の部位をクリックしてからXYZ矢印をドラッグ",
    "Drag the XYZ arrows, or drag the body part in the camera plane; hold Alt for depth": "XYZ矢印をドラッグするか、画面上で身体の部位をドラッグします。Altを押しながら前後方向を調整できます",
    "Click a body part, then drag it or use the rotation rings": "身体の部位をクリックし、直接ドラッグするか回転リングで調整します",
    "Drag vertically for local X, horizontally for local Z; hold Alt for local Y": "縦ドラッグでローカルX、横ドラッグでローカルZ、Altを押しながらローカルYを調整します",
    "No weighted bone at this point": "この位置に編集可能なウェイト付きボーンはありません",
    "Selected bone": "選択中のボーン",
    "Model part": "モデルパーツ",
    "Model part visibility": "モデルパーツの表示",
    "Model part search": "モデルパーツ検索",
    "Search model parts": "モデルパーツを検索",
    "No model parts": "切り替え可能なモデルパーツはありません",
    "Selected model part": "選択中のモデルパーツ",
    "No model part selected": "モデルパーツが選択されていません",
    "Hide selected part": "選択したパーツを非表示",
    "Show selected part": "選択したパーツを表示",
    "Show all parts": "すべてのパーツを表示",
    "Hidden": "非表示",
    "Common body controls": "主要ボーン設定",
    "All bone controls": "すべてのボーン設定",
    "Common expression controls": "主要表情設定",
    "All expression controls": "すべての表情設定",
    "Character movement": "キャラクターの回転・移動",
    "Show character movement": "キャラクター移動を表示",
    "Hide character movement": "キャラクター移動を閉じる",
    "Rotate character left": "キャラクターを左回転",
    "Rotate character right": "キャラクターを右回転",
    "Tilt character left": "キャラクターを左に傾ける",
    "Tilt character right": "キャラクターを右に傾ける",
    "Turn character left": "キャラクターを左へ向ける",
    "Turn character right": "キャラクターを右へ向ける",
    "Move character up": "キャラクターを上へ移動",
    "Move character down": "キャラクターを下へ移動",
    "Move character left": "キャラクターを左へ移動",
    "Move character right": "キャラクターを右へ移動",
    "Reset character transform": "キャラクターの位置と向きをリセット",
    "Capture character": "キャラクターのみ撮影",
    "Capture with background": "背景付きで撮影",
    "Record character": "キャラクターのみ録画",
    "Record with background": "背景付きで録画",
    "Record MP4 with background": "背景付きMP4を録画",
    "Char Only": "キャラのみ",
    "With BG": "背景付き",
    "Rec Char": "キャラ録画",
    "Rec/BG": "録画／背景",
    "MP4/BG": "MP4／背景",
    "Stop": "停止",
    "Stop recording": "録画を停止",
    "Video recording is not supported by this browser": "このブラウザーは動画録画に対応していません",
    "Video recording could not be started": "動画録画を開始できませんでした",
    "Video recording could not be completed": "動画録画を完了できませんでした",
    "Recording format": "録画形式",
    "Recording resolution": "録画解像度",
    "Current view": "現在の画面",
    "Recording aspect ratio": "録画アスペクト比",
    "Recording orientation": "録画方向",
    "Quality": "画質",
    "Aspect ratio": "アスペクト比",
    "Orientation": "向き",
    "Landscape": "横向き",
    "Portrait": "縦向き",
    "WebM duration metadata could not be written": "WebMの再生時間メタデータを書き込めませんでした",
    "Enter VR": "VRを開始",
    "Exit VR": "VRを終了",
    "VR is not available in this browser": "このブラウザーではVRを利用できません",
    "No immersive VR device is available": "利用可能な没入型VRデバイスがありません",
    "VR session could not be started": "VRセッションを開始できませんでした",
    "Viewer tools": "ビューアーツール",
    "Visit the Magius3Dviewer source branch": "Magius3Dviewerのソースブランチを開く",
    "Use light theme": "ライトテーマを使用",
    "Use dark theme": "ダークテーマを使用",
    "Change background": "背景を変更",
    "Choose from album": "ローカル画像を選択",
    "Select camera mode": "カメラモードを選択",
    "Camera background": "カメラ背景",
    "Turn off camera background": "カメラ背景を停止",
    "Fullscreen": "全画面",
    "Adjust character position": "キャラクター位置を調整",
    "Adjust character rotation": "キャラクター回転を調整",
    "Preset": "プリセット",
    "OK": "決定",
    "Close": "閉じる",
    "Download": "ダウンロード",
    "< Select a character to add >": "<追加するキャラクターを選択>",
    "<No animation>": "<アニメーションなし>",
    "<No expression data>": "<表情データなし>",
    "Please copy the preset link below:": "以下のプリセットリンクをコピーしてください：",
    "Waiting for clipboard read permission; try again shortly": "クリップボードの読み取り許可を待っています。しばらくしてから再試行してください",
    "Enter preset link:": "プリセットリンクを入力：",
    "Invalid preset content": "プリセットの内容が正しくありません",
    "Photo capture failed": "撮影に失敗しました",
    "Show outline even when mesh is hidden": "メッシュ非表示時もアウトラインを表示",
    "Show outline even when mesh parts are hidden": "メッシュパーツ非表示時もアウトラインを表示",
    "Copied to clipboard!": "クリップボードにコピーしました！",
    "3D Stage": "3Dステージ",
    "Stage Runtime": "ステージランタイム",
    "Stage fidelity / evidence": "ステージ再現度／根拠",
    "Inspect recovered scene provenance and remaining fidelity gaps": "復元したシーンの出典と残っている再現差分を確認",
    "Stage ID": "ステージID",
    "Category": "カテゴリ",
    "Official asset": "公式アセット",
    "Dynamic status": "動的状態",
    "Region": "地域",
    "AssetBundle": "AssetBundle",
    "Manifest sources": "マニフェスト出典",
    "Direct dependencies": "直接依存",
    "Dependency closure": "依存関係全体",
    "Closure SHA-256": "依存関係全体のSHA-256",
    "Render profile": "レンダープロファイル",
    "Recovered components": "復元済みコンポーネント",
    "Lightmap": "ライトマップ",
    "Environment map": "環境マップ",
    "Runtime clips": "ランタイムクリップ",
    "Typetree errors": "TypeTreeエラー",
    "Manifest provenance": "マニフェストの出典",
    "Remaining fidelity gaps": "残っている再現差分",
    "Recovered evidence": "復元根拠",
    "No declared dynamic gaps": "宣言済みの動的差分はありません",
    "No structured gap list": "構造化された差分一覧はありません",
    "No evidence attached": "根拠は添付されていません",
    "Yes": "はい",
    "No": "いいえ",
    "Reset stage transform": "ステージ変形をリセット",
    "Place characters at stage spawns": "キャラクターをステージ開始位置へ配置",
    "Seek (seconds)": "シーク（秒）",
    "Time scale": "時間倍率",
    "Physics action options": "物理アクションオプション",
    "Loading physics action options...": "物理アクションオプションを読み込み中…",
    "Physics phases": "物理アクションフェーズ",
    "Related official actions": "関連する公式アクション",
    "Special skill reserve": "必殺技待機フェーズ",
    "Special skill reserve and pre-special": "必殺技待機・発動前フェーズ",
    "Awaiting official action phase consumer": "公式アクションフェーズ接続待機中",
    "Activate phase": "フェーズを有効化",
    "Phase active": "フェーズ有効",
    "Release phase": "フェーズを解除",
    "Activating...": "有効化中…",
    "Activating physics phase...": "物理フェーズを有効化中…",
    "Physics phase active": "物理フェーズ有効",
    "Action-owned phase root": "公式アクション所有フェーズルート",
    "External phase root": "外部フェーズルート",
    "Ready for active official action": "現在の公式アクションに接続できます",
    "Play an official action before activating this phase": "先にこのキャラクターの公式アクションを再生してください",
    "No physics action phases for this character": "このキャラクターの物理アクションフェーズはありません",
    "No related official actions for this character": "このキャラクターに関連する公式アクションはありません",
    "Physics action options unavailable": "物理アクションオプションを利用できません",
    "Select a character to view physics action options": "キャラクターを選択すると物理アクションオプションを表示します",
    "Play": "再生",
    "Pause": "一時停止",
    "Restart": "最初から再生",
    "Visible": "表示",
    "RotateY": "Y回転",
    "Scale": "スケール",
    "Reset": "リセット",
    "Character (Selected)": "キャラクター（選択中）",
    "Characters (Global)": "キャラクター（全体）",
    "Outline": "アウトライン",
    "Meshes": "メッシュ",
    "OutlineVisible": "アウトライン表示",
    "OutlineThickness": "アウトラインの太さ",
    "OutlineColor": "アウトライン色",
    "OutlineAlwaysVisible": "アウトラインを常に表示",
    "Arrange in line": "直線状に配置",
    "Arrange in arc": "円弧状に配置",
    "Center all": "すべて中央へ配置",
    "RotateX": "X回転",
    "RotateZ": "Z回転",
    "AnimationSpeed": "アニメーション速度",
    "Reset character": "キャラクターをリセット",
    "Color": "色",
    "Brightness": "明るさ",
    "Contrast": "コントラスト",
    "Saturation": "彩度",
    "Camera": "カメラ",
    "FOV": "視野角（FOV）",
    "CameraRotation": "カメラ回転",
    "CameraResolution": "カメラ解像度",
    "CurrentResolution": "現在の解像度",
    "CameraFullscreen": "カメラを全画面表示",
    "Reset camera": "カメラをリセット",
    "Lighting": "ライティング",
    "BgColor": "背景色",
    "AmbientLightColor": "環境光色",
    "DirectionalLightColor": "平行光源色",
    "AmbientLight": "環境光",
    "DirectionalLight": "平行光源",
    "LightAngle": "光源角度",
    "LightHeight": "光源高さ",
    "LightDistance": "光源距離",
    "Bloom": "ブルーム",
    "BloomStrength": "ブルーム強度",
    "BloomRadius": "ブルーム半径",
    "BloomThreshold": "ブルームしきい値",
    "CameraEnvironment": "カメラ環境光",
    "DynamicAmbient": "動的環境反射",
    "DynamicLight": "動的メインライト",
    "Reset lighting": "ライティングをリセット",
    "Shader": "シェーダー",
    "Apply recovered ReDrive baseline": "復元済みReDrive基準を適用",
    "Legacy colour blend (debug only)": "旧カラー合成（デバッグ専用）",
    "Override exact scene lighting": "シーンの正確なライティングを上書き",
    "Physical light influence": "物理ライトの影響",
    "Albedo lift": "アルベド持ち上げ",
    "Shadow tint": "影色",
    "Shadow tint strength": "影色の強さ",
    "Highlight tint": "ハイライト色",
    "Highlight tint strength": "ハイライト色の強さ",
    "Control B / gradient specular": "Control B／グラデーションスペキュラー",
    "Control G response tint": "Control G応答色",
    "Toon shadow selection": "トゥーン影選択",
    "Control R pre-mix": "Control R事前合成",
    "Light probe value": "ライトプローブ値",
    "Shadow threshold": "影しきい値",
    "Shadow softness": "影の柔らかさ",
    "Ambient shadow amount": "環境影量",
    "Control R threshold offset": "Control Rしきい値オフセット",
    "AngelRing (official GLES projection)": "AngelRing（公式GLES投影）",
    "Diagnostic A/B toggle": "診断A/B切り替え",
    "Timeline / scene additional Rim": "タイムライン／シーン追加リムライト",
    "Enabled": "有効",
    "HDR color approximation": "HDR色近似",
    "Strength": "強さ",
    "Threshold": "しきい値",
    "Feather": "ぼかし",
    "Direction X": "方向X",
    "Direction Y": "方向Y",
    "Directionality": "方向性",
    "Per-renderer animation Fresnel": "レンダラー別アニメーションフレネル",
    "Global debug override": "グローバルデバッグ上書き",
    "Shadow": "影",
    "ShadowEnabled": "影を有効化",
    "ShadowType": "影タイプ",
    "ShadowResolution": "影解像度",
    "ShadowBias": "影バイアス",
    "FloorShadowOpacity": "床影の不透明度",
    "ShadowAlphaTest": "影アルファテスト",
    "ShadowCameraHelper": "影カメラ補助表示",
    "ShadowCameraSize": "影カメラ範囲",
    "ShadowCameraOffsetX": "影カメラXオフセット",
    "ShadowCameraOffsetY": "影カメラYオフセット",
    "Misc": "その他",
    "Axes": "座標軸",
    "PixelRatio": "ピクセル倍率",
    "UseEffectComposer": "ポスト処理合成を使用",
    "AntiAliasing(Composer)": "アンチエイリアス（ポスト処理）",
    "AntiAliasingLevel": "アンチエイリアスレベル",
    "PerformanceMetrics": "パフォーマンス指標",
    "Auto": "自動",
    "Always": "常に",
    "Never": "使用しない",
    "None": "なし",
    "Export presets": "プリセットを書き出す",
    "Import presets": "プリセットを読み込む",
    "Reset everything": "すべてリセット",
    "START AR": "ARを開始",
    "STOP AR": "ARを停止",
    "AR NOT SUPPORTED": "ARはサポートされていません",
    "AR NOT ALLOWED": "ARの利用が許可されていません"
}

const jaJpUiTextPatterns: ReadonlyArray<readonly [RegExp, string]> = [
    [/^Stage fidelity \/ evidence — (.+)$/, 'ステージ再現度／根拠 — $1'],
    [/^\[Research\]\s*/, '[研究] '],
    [/^\[Official geometry\/([^\]]+)\]\s*/, '[公式ジオメトリ／$1] '],
    [/^\[Official dynamic partial\/([^\]]+)\]\s*/, '[公式動的（部分）／$1] '],
    [/^\[Official dynamic\/([^\]]+)\]\s*/, '[公式動的／$1] '],
    [/^\[Official\/([^\]]+)\]\s*/, '[公式／$1] '],
    [/^Loading FBX\.\.\.$/, 'FBXモデルを読み込んでいます…'],
    [/^Loading textures\.\.\.$/, 'テクスチャを読み込んでいます…'],
    [/^Loading (\d+) \/ (\d+) models\.\.\.$/, 'モデルを読み込んでいます：$1／$2…'],
    [/^Import preset with (\d+) characters\?$/, '$1体のキャラクターを含むプリセットを読み込みますか？'],
    [/^Auto: Use effect composer only when needed[\s\S]*$/, '自動：選択アウトラインなど必要な場合のみポスト処理を使用します。\n常に：常にポスト処理を使用し、直接描画を無効にします。\n使用しない：ポスト処理を無効にして常に直接描画します（選択アウトラインは表示されません）。\n\n高品質なアンチエイリアスを強制すると画質は向上しますが、パフォーマンスは低下します。'],
    [/^Anti-aliasing method used for the effect composer[\s\S]*$/, 'ポスト処理で使用するアンチエイリアス方式です。\n常に既定のMSAAを使う直接描画には影響しません。'],
]

const jaOfficialExpressionLabels: Readonly<Record<string, string>> = {
    Smile: '微笑み', Smiling: '笑顔', Serious: '真剣', Annoyed: '不機嫌', Furious: '激怒',
    Sorrow: '悲哀', Sadness: '悲しみ', Troubled: '困惑', Dumbfounded: '呆然', Wry: '苦笑',
    Surprised: '驚き', Astonished: '驚愕', Damage: 'ダメージ', Expressionless: '無表情', Despair: '絶望',
}

const jaOfficialAnimationBaseLabels: Readonly<Record<string, string>> = {
    Abnormality: '異常状態', CommonWait: '共通待機', Damage: 'ダメージ', Down: 'ダウン',
    HomeUnique01: 'ホーム専用アクション1', HomeWait01: 'ホーム待機1', HomeWait02: 'ホーム待機2',
    HomeWait0102: 'ホーム待機1→2', HomeTransition01: 'ホーム遷移1', StandbyTransition: '戦闘待機遷移',
    Standby: '戦闘待機', Victory: '勝利', Wait: '待機', Attack: '攻撃', Skill: 'スキル',
    Magia: 'マギア', Guard: '防御', Dodge: '回避', Run: '走る', Walk: '歩く', Entry: '登場',
    Appear: '出現', Death: '退場',
}

const jaAnimationSuffixLabels: Readonly<Record<string, string>> = { L: 'ループ', S: '開始', SE: '単発' }

const jaBoneSemanticLabels: ReadonlyArray<readonly [RegExp, string]> = [
    [/(?:^|[_ .:/-])(?:root|origin)(?:$|[_ .:/-])/i, 'ルートボーン'], [/(?:hip|hips|pelvis)/i, '骨盤'],
    [/(?:waist|center)/i, '腰'], [/(?:spine)/i, '背骨'], [/(?:chest|bust)/i, '胸'],
    [/(?:neck)/i, '首'], [/(?:head)/i, '頭'], [/(?:clavicle|shoulder)/i, '肩'],
    [/(?:forearm|lowerarm)/i, '前腕'], [/(?:upperarm)/i, '上腕'], [/(?:elbow)/i, '肘'],
    [/(?:hand|wrist)/i, '手'], [/(?:thigh|upperleg)/i, '太もも'], [/(?:calf|shin|lowerleg)/i, 'すね'],
    [/(?:knee)/i, '膝'], [/(?:foot|ankle)/i, '足'], [/(?:toe)/i, 'つま先'],
]

const jaTechnicalTokenLabels: Readonly<Record<string, string>> = {
    left:'左',l:'左',right:'右',r:'右',center:'中央',c:'中央',root:'ルートボーン',origin:'原点',
    hip:'腰',hips:'腰',pelvis:'骨盤',waist:'腰',spine:'背骨',chest:'胸',bust:'胸',neck:'首',head:'頭',
    clavicle:'鎖骨',shoulder:'肩',upperarm:'上腕',arm:'腕',forearm:'前腕',lowerarm:'前腕',elbow:'肘',
    hand:'手',wrist:'手首',finger:'指',thumb:'親指',thigh:'太もも',upperleg:'太もも',leg:'脚',
    lowerleg:'すね',calf:'すね',shin:'すね',knee:'膝',foot:'足',ankle:'足首',toe:'つま先',twist:'ひねり',roll:'回転',
    eye:'目',eyes:'目',eyelid:'まぶた',brow:'眉',eyebrow:'眉',eyebrows:'眉',blink:'まばたき',open:'開く',opened:'開く',
    close:'閉じる',closed:'閉じる',smile:'微笑み',smiling:'笑顔',mouth:'口',lip:'唇',corner:'口角',cheek:'頬',
    tear:'涙',tongue:'舌',jaw:'顎',face:'顔',up:'上',down:'下',lower:'下部',upper:'上部',inside:'内側',outside:'外側',
    inner:'内側',outer:'外側',forward:'前',back:'後ろ',long:'長',short:'短',form:'形',shape:'形',anger:'怒り',
    angry:'怒り',sad:'悲しみ',sorrow:'悲哀',damage:'ダメージ',motion:'モーション',mtn:'モーション',
    animation:'アニメーション',anim:'アニメーション',home:'ホーム',wait:'待機',standby:'戦闘待機',transition:'遷移',
    victory:'勝利',attack:'攻撃',skill:'スキル',magia:'マギア',guard:'防御',dodge:'回避',run:'走る',walk:'歩く',
    entry:'登場',appear:'出現',death:'退場',loop:'ループ',expression:'表情',facial:'表情',
}

function splitJaTechnicalTokens(value: string): string[] {
    return value.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/([A-Z])([A-Z][a-z])/g, '$1 $2')
        .split(/[_ .:/\\-]+/).filter(Boolean)
}

function translateJaTechnicalTokens(value: string): string | undefined {
    const tokens = splitJaTechnicalTokens(value)
    let translated = false
    const label = tokens.map(token => {
        const mapped = jaTechnicalTokenLabels[token.toLocaleLowerCase()]
        if (mapped) translated = true
        return mapped ?? token
    }).join(' ')
    return translated ? label : undefined
}

function translateJaOfficialRuntimeOption(text: string): string | undefined {
    const canonical = text.trim()
    const expression = jaOfficialExpressionLabels[canonical]
    if (expression) return expression
    const special: Readonly<Record<string, string>> = {
        HomeWait02transition: 'ホーム待機2 遷移', transition_HomeWait01: 'ホーム待機1 遷移',
        W_HomeWait01_L: '武器ホーム待機1（ループ）',
    }
    if (special[canonical]) return special[canonical]
    const match = canonical.match(/^(.+?)_(SE|S|L)$/)
    const base = match?.[1] ?? canonical
    const suffix = match?.[2]
    const baseLabel = jaOfficialAnimationBaseLabels[base]
    if (baseLabel) return suffix ? `${baseLabel}（${jaAnimationSuffixLabels[suffix]}）` : baseLabel
    const technical = translateJaTechnicalTokens(base)
    return technical ? (suffix ? `${technical}（${jaAnimationSuffixLabels[suffix]}）` : technical) : undefined
}

export function translateJaJpUiText(text: string): string {
    if (!text) return text
    const exact = jaJpUiText[text]
    if (exact) return exact
    for (const [pattern, replacement] of jaJpUiTextPatterns) {
        if (pattern.test(text)) return text.replace(pattern, replacement)
    }
    return translateJaOfficialRuntimeOption(text) ?? text
}

export function translateJaJpBoneChannelLabel(name: string): string {
    if (!name) return name
    const side = /(?:^|[_ .:/-])(?:left|l)(?:$|[_ .:/-])/i.test(name) || /^L(?=[A-Z])/.test(name)
        ? '左' : /(?:^|[_ .:/-])(?:right|r)(?:$|[_ .:/-])/i.test(name) || /^R(?=[A-Z])/.test(name) ? '右' : ''
    const semantic = jaBoneSemanticLabels.find(([pattern]) => pattern.test(name))?.[1]
    if (semantic) {
        const detail = /(?:twist|roll)/i.test(name) ? '（ひねり）' : ''
        const number = name.match(/\d+$/)?.[0]
        return `${side}${semantic}${detail}${number ? ` ${number}` : ''}`
    }
    return translateJaTechnicalTokens(name) ?? name
}

export function translateJaJpMorphChannelLabel(name: string): string {
    return name ? translateJaTechnicalTokens(name) ?? name : name
}

