#!/usr/bin/env python3
"""Generate Web draw groups from official Unity Mesh submeshes.

AssetStudio's FBX export keeps the material-name array but can flatten the
ByPolygon material layer.  Three's FBXLoader then returns a non-indexed geometry
without groups, so only slot zero is rendered.  The official Unity Mesh still
contains exact, contiguous m_SubMeshes.  This tool reads one small character
bundle at a time and emits only index counts; no mesh buffers are retained.
"""

from __future__ import annotations

import argparse
import gc
import json
from pathlib import Path
import re

import UnityPy


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--style-list", required=True, type=Path)
    parser.add_argument(
        "--model-root",
        required=True,
        type=Path,
        help="Viewer model directory; its chara_<id>_battle_unit folders define the runtime corpus.",
    )
    parser.add_argument("--bundle-root", required=True, type=Path)
    parser.add_argument(
        "--home-bundle-root",
        type=Path,
        default=None,
        help=(
            "Official home bundle directory for chara_<id>_model actors; "
            "defaults to <AssetBundles>/home beside battle/character."
        ),
    )
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--unity-version", default="2022.3.62f2")
    return parser.parse_args()


def load_style_catalog(path: Path) -> tuple[set[int], set[str]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    rows = payload.get("result", payload)
    if isinstance(rows, dict) and isinstance(rows.get("payload"), dict):
        rows = rows["payload"]
    if isinstance(rows, dict):
        for key in ("mstList", "style3dCharacterMstList", "list", "data"):
            if isinstance(rows.get(key), list):
                rows = rows[key]
                break
    if not isinstance(rows, list):
        raise ValueError(f"Unsupported style list structure: {path}")
    style_ids = {
        int(row["style3dCharacterMstId"])
        for row in rows
        if isinstance(row, dict) and row.get("style3dCharacterMstId") is not None
    }
    resource_names = {
        str(row["resourceName"])
        for row in rows
        if isinstance(row, dict) and row.get("resourceName")
    }
    return style_ids, resource_names


def load_runtime_resource_names(
    model_root: Path,
    style_ids: set[int],
    catalog_resource_names: set[str],
) -> list[str]:
    """Return the exact battle-model corpus addressed by the Viewer runtime.

    A style ID and its resourceName are not interchangeable.  For example,
    style 100101 currently references chara_100107_battle_unit in master data,
    while the Viewer also contains an independently exported
    chara_100101_battle_unit.  Keying this table only from resourceName silently
    omitted the latter and emitted an unused 100102 entry.  The local model
    directory is therefore the runtime key set; the style catalog is used only
    to reject unexplained folders rather than to alias one character's ranges.
    """
    resources: list[str] = []
    unknown: list[str] = []
    for child in sorted(model_root.iterdir(), key=lambda value: value.name):
        if not child.is_dir():
            continue
        match = re.fullmatch(
            r"chara_(\d+)(?:_(?:battle_unit|model))?",
            child.name,
        )
        if not match:
            continue
        character_id = int(match.group(1))
        if character_id not in style_ids and child.name not in catalog_resource_names:
            unknown.append(child.name)
            continue
        resources.append(child.name)
    if unknown:
        raise ValueError(
            "Viewer battle-model folders absent from the official style catalog: "
            + ", ".join(unknown)
        )
    if not resources:
        raise ValueError(
            f"No chara_<id>[_battle_unit|_model] folders found under {model_root}"
        )
    return resources


def read_bundle(path: Path) -> dict[str, list[int]]:
    env = UnityPy.load(str(path))
    result: dict[str, list[int]] = {}
    try:
        for obj in env.objects:
            if obj.type.name != "Mesh":
                continue
            mesh = obj.read()
            name = str(getattr(mesh, "m_Name", ""))
            counts = [
                int(getattr(submesh, "indexCount", 0))
                for submesh in (getattr(mesh, "m_SubMeshes", None) or [])
            ]
            if name and counts and all(count > 0 for count in counts):
                result[name] = counts
    finally:
        del env
        gc.collect()
    return result


def emit(output: Path, profiles: dict[int, dict[str, list[int]]]) -> None:
    lines = [
        "// Generated by scripts/generate-jp-character-submesh-groups.py.",
        "// Source: JP Steam Unity 2022.3.62f2 battle/character and home bundles for the local Viewer model corpus.",
        "export const officialCharacterSubmeshIndexCounts: Readonly<",
        "    Record<number, Readonly<Record<string, readonly number[]>>>",
        "> = {",
    ]
    for character_id in sorted(profiles):
        lines.append(f"    {character_id}: {{")
        for mesh_name, counts in sorted(profiles[character_id].items()):
            encoded = ", ".join(str(value) for value in counts)
            lines.append(f"        {json.dumps(mesh_name)}: [{encoded}],")
        lines.append("    },")
    lines.extend(["};", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("\n".join(lines))


def main() -> int:
    args = parse_args()
    UnityPy.config.FALLBACK_UNITY_VERSION = args.unity_version
    style_ids, catalog_resource_names = load_style_catalog(args.style_list)
    resource_names = load_runtime_resource_names(
        args.model_root,
        style_ids,
        catalog_resource_names,
    )
    profiles: dict[int, dict[str, list[int]]] = {}
    missing: list[str] = []
    home_bundle_root = args.home_bundle_root
    if home_bundle_root is None:
        home_bundle_root = args.bundle_root.parent.parent / "home"
    for resource_name in resource_names:
        match = re.fullmatch(
            r"chara_(\d+)(?:_(battle_unit|model))?",
            resource_name,
        )
        if not match:
            continue
        kind = match.group(2) or "battle_unit"
        bundle_name = resource_name if match.group(2) else (
            f"chara_{match.group(1)}_battle_unit"
        )
        bundle = (
            args.bundle_root if kind == "battle_unit" else home_bundle_root
        ) / bundle_name
        if not bundle.is_file():
            missing.append(resource_name)
            continue
        meshes = read_bundle(bundle)
        if meshes:
            profiles[int(match.group(1))] = meshes
        print(f"{resource_name}: {len(meshes)} meshes", flush=True)
    emit(args.output, profiles)
    print(
        json.dumps(
            {
                "profiles": len(profiles),
                "runtimeModels": len(resource_names),
                "missing": missing,
                "output": str(args.output),
            },
            ensure_ascii=False,
        ),
        flush=True,
    )
    return 0 if not missing else 2


if __name__ == "__main__":
    raise SystemExit(main())
