#!/usr/bin/env python3
"""Generate Web draw groups from official Unity Mesh submeshes.

AssetStudio's FBX export keeps the material-name array but can flatten the
ByPolygon material layer.  Three's FBXLoader then returns a non-indexed geometry
without groups, so only slot zero is rendered.  The official Unity Mesh still
contains exact, contiguous m_SubMeshes.  This tool reads one small character
bundle at a time and emits only index counts; no mesh buffers are retained.
"""

from __future__ import annotations

import argparse
import gc
import json
from pathlib import Path
import re

import UnityPy


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--style-list", required=True, type=Path)
    parser.add_argument("--bundle-root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--unity-version", default="2022.3.62f2")
    return parser.parse_args()


def load_resource_names(path: Path) -> list[str]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    rows = payload.get("result", payload)
    if isinstance(rows, dict) and isinstance(rows.get("payload"), dict):
        rows = rows["payload"]
    if isinstance(rows, dict):
        for key in ("mstList", "style3dCharacterMstList", "list", "data"):
            if isinstance(rows.get(key), list):
                rows = rows[key]
                break
    if not isinstance(rows, list):
        raise ValueError(f"Unsupported style list structure: {path}")
    return sorted({
        str(row["resourceName"])
        for row in rows
        if isinstance(row, dict) and row.get("resourceName")
    })


def read_bundle(path: Path) -> dict[str, list[int]]:
    env = UnityPy.load(str(path))
    result: dict[str, list[int]] = {}
    try:
        for obj in env.objects:
            if obj.type.name != "Mesh":
                continue
            mesh = obj.read()
            name = str(getattr(mesh, "m_Name", ""))
            counts = [
                int(getattr(submesh, "indexCount", 0))
                for submesh in (getattr(mesh, "m_SubMeshes", None) or [])
            ]
            if name and counts and all(count > 0 for count in counts):
                result[name] = counts
    finally:
        del env
        gc.collect()
    return result


def emit(output: Path, profiles: dict[int, dict[str, list[int]]]) -> None:
    lines = [
        "// Generated by scripts/generate-jp-character-submesh-groups.py.",
        "// Source: JP 3.11 Unity 2022.3.62f2 battle/character bundles.",
        "export const officialCharacterSubmeshIndexCounts: Readonly<",
        "    Record<number, Readonly<Record<string, readonly number[]>>>",
        "> = {",
    ]
    for character_id in sorted(profiles):
        lines.append(f"    {character_id}: {{")
        for mesh_name, counts in sorted(profiles[character_id].items()):
            encoded = ", ".join(str(value) for value in counts)
            lines.append(f"        {json.dumps(mesh_name)}: [{encoded}],")
        lines.append("    },")
    lines.extend(["};", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    UnityPy.config.FALLBACK_UNITY_VERSION = args.unity_version
    profiles: dict[int, dict[str, list[int]]] = {}
    missing: list[str] = []
    for resource_name in load_resource_names(args.style_list):
        match = re.search(r"chara_(\d+)_battle_unit", resource_name)
        if not match:
            continue
        bundle = args.bundle_root / resource_name
        if not bundle.is_file():
            missing.append(resource_name)
            continue
        meshes = read_bundle(bundle)
        if meshes:
            profiles[int(match.group(1))] = meshes
        print(f"{resource_name}: {len(meshes)} meshes", flush=True)
    emit(args.output, profiles)
    print(
        json.dumps(
            {
                "profiles": len(profiles),
                "missing": missing,
                "output": str(args.output),
            },
            ensure_ascii=False,
        ),
        flush=True,
    )
    return 0 if not missing else 2


if __name__ == "__main__":
    raise SystemExit(main())
